In [ ]:
#Python- Pnadas trial
#https://www.kaggle.com/code/icarofreire/pandas-24-useful-exercises-with-solutions

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Input

a_list = list("abcdefg")
numpy_array = np.arange(1, 10)
dictionary = {"A":  0, "B":1, "C":2, "D":3, "E":5}

In [3]:
series1 = pd.Series(a_list)
print(series1)
series2 = pd.Series(numpy_array)
print(series2)
series3 = pd.Series(dictionary)
print(series3)

0    a
1    b
2    c
3    d
4    e
5    f
6    g
dtype: object
0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
A    0
B    1
C    2
D    3
E    5
dtype: int64

In [10]:
#2. How to combine many series to form a dataframe?
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

ser_df=pd.DataFrame(ser1, ser2).reset_index()
ser_df.head()

   index  0
0      0  a
1      1  b
2      2  c
3      3  e
4      4  d

In [11]:
ser_df = pd.DataFrame({'col1':ser1, 'col2':ser2})
ser_df.head(5)

  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [12]:
ser_df = pd.concat([ser1, ser2], axis = 1)
ser_df.head()

   0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4

In [3]:
#3. How to get the items of series A not present in series B?
# input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

a= [x for x in list(ser1) if x not in list(ser2)] 
a
ser1[~ser1.isin(ser2)], a

(0    1
 1    2
 2    3
 dtype: int64,
 [1, 2, 3])

In [17]:
#4. How to get the items not common to both series A and series B?
# input
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8, 9])

Nser1=ser1[~ser1.isin(ser2)]
Nser2=ser2[~ser2.isin(ser1)]
print(Nser1)
list(Nser1)+list(Nser2) #, ignore_index=True)

0    1
1    2
2    3
dtype: int64

[1, 2, 3, 6, 7, 8, 9]

In [23]:
a=[1,2,3]
b=[3,5,2]
c=a+b
print(c)
[x+y for i,x in enumerate(a) for j,y in enumerate(b) if i==j]

[1, 2, 3, 3, 5, 2]

[4, 7, 5]

In [30]:
#Compute the minimum, 25th percentile, median, 75th, and maximum of ser.
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))

state, ser
mini,p25,p50,p75,p100 = np.percentile(ser, [0,25,50,75,100])
mini,p25,p50,p75,p100
#or using pandas

mini,p25,p50,p75,p100, ser.describe()

(1.2511726347265135,
 7.7098650724868785,
 10.922593452819715,
 13.363604028548306,
 18.0949083033763,
 count    25.000000
 mean     10.435437
 std       4.253118
 min       1.251173
 25%       7.709865
 50%      10.922593
 75%      13.363604
 max      18.094908
 dtype: float64)

In [5]:
#Calculate the frequency counts of each unique value ser.
ind=np.random.randint(8, size=30)
ser = pd.Series(np.take(list('abcdefgh'), ind))

ser, ind, ser.value_counts()

(0     h
 1     f
 2     a
 3     e
 4     g
 5     c
 6     b
 7     h
 8     b
 9     b
 10    h
 11    e
 12    a
 13    h
 14    h
 15    e
 16    f
 17    g
 18    c
 19    e
 20    d
 21    b
 22    b
 23    b
 24    c
 25    h
 26    g
 27    c
 28    c
 29    e
 dtype: object,
 array([7, 5, 0, 4, 6, 2, 1, 7, 1, 1, 7, 4, 0, 7, 7, 4, 5, 6, 2, 4, 3, 1,
        1, 1, 2, 7, 6, 2, 2, 4]),
 h    6
 b    6
 e    5
 c    5
 g    3
 f    2
 a    2
 d    1
 dtype: int64)

In [177]:
#Reshape the series ser into a dataframe with 7 rows and 5 columns

nparray= np.arange(0,35).reshape(7,5)
# using only pandas
ser=pd.Series(np.random.randint(1, 10, 35))
ser_arr=pd.DataFrame(ser.values.reshape(7, 5))
#ser_arr=pd.DataFrame(nparray)
nparray, ser_arr, type(ser_arr)

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]]),
    0  1  2  3  4
 0  5  3  5  4  3
 1  2  4  9  2  3
 2  6  9  3  3  5
 3  8  9  6  4  6
 4  1  7  7  8  4
 5  6  9  4  1  7
 6  5  6  6  4  3,
 pandas.core.frame.DataFrame)

In [26]:
#Find the positions of numbers that are multiples of 3 from ser.
#np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 10, 10))
mul3=[i for i,x in enumerate(ser) if x%3 ==0]
ser, mul3

(0    2
 1    4
 2    8
 3    3
 4    8
 5    3
 6    7
 7    2
 8    9
 9    2
 dtype: int64,
 [3, 5, 8])

In [29]:
#From ser, extract the items at positions in list pos.
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20, 8]

print(ser.iloc[pos], ser.loc[pos])
ser=list(ser)
l=[x for i,x in enumerate(ser) if i in pos]
print (l)

0     a
4     e
8     i
14    o
20    u
8     i
dtype: object 0     a
4     e
8     i
14    o
20    u
8     i
dtype: object
['a', 'e', 'i', 'o', 'u']

In [63]:
#stack ser1 and ser2 vertically and horizontally (to form a dataframe).
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

print(pd.concat([ser1,ser2], axis=1))
pd.concat([ser1,ser2], axis=0,ignore_index=True)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

0    0
1    1
2    2
3    3
4    4
5    a
6    b
7    c
8    d
9    e
dtype: object

In [88]:
#Get the positions of items of ser2 in ser1 as a list.
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

[i for i,x in enumerate(list(ser2)) if x in list(ser1)] 

list(ser2[ser2.isin(ser1)].index), [i for i,x in enumerate(list(ser2)) if x in list(ser1)]

([0, 1, 2, 3], [0, 1, 2, 3])

In [31]:
#Difference of differences between the consequtive numbers of ser.
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
list(ser.diff()), list(ser.diff().diff())

([nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0],
 [nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0])

In [78]:
#How to convert a series of date-strings to a timeseries?
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

from datetime import datetime

pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [104]:
#How to filter words that contain atleast 2 vowels from a series?
from collections import Counter
ser = pd.Series(['Aappl', 'Orange', 'Plan', 'Python', 'Money'])

#mask=ser.map(lambda x: sum([Counter(x.lower()).get(i,0) for i in list('aeiou')])>=2)
mask=ser.map(lambda x: sum([Counter(x.lower()).get(i,0) for i in list('aeiou')])>=2)
ser[mask], [x[0].lower()+x[1:] for x in ser]

(0     Aappl
 1    Orange
 4     Money
 dtype: object,
 ['aappl', 'orange', 'plan', 'python', 'money'])

In [95]:
#15. How to replace missing spaces in a string with the least frequent character?
my_str = 'dbc deb abed ggade'
my_str=list(my_str)
print(my_str)
#my_str=pd.Series(my_str)
print(my_str)
print(pd.Series(my_str).value_counts().index[-1])
#min([x for my_str.count(x)])
print(pd.Series(list(my_str)).value_counts(ascending=True).index[0])
#my_str1="".join(my_str.replace(" ", pd.Series(list(my_str)).value_counts().index[-1]))
my_str1="".join(str(my_str).replace(" ", str(pd.Series(my_str).value_counts().index[-1])))
my_str1

['d', 'b', 'c', ' ', 'd', 'e', 'b', ' ', 'a', 'b', 'e', 'd', ' ', 'g', 'g', 'a', 'd', 'e']
['d', 'b', 'c', ' ', 'd', 'e', 'b', ' ', 'a', 'b', 'e', 'd', ' ', 'g', 'g', 'a', 'd', 'e']
c
c

"['d',c'b',c'c',c'c',c'd',c'e',c'b',c'c',c'a',c'b',c'e',c'd',c'c',c'g',c'g',c'a',c'd',c'e']"

In [107]:
#How to get the last n rows (5) of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df1 = df.copy(deep = True)
df['sum']=df.sum(axis=1)
df1[df1.sum(axis=1)>100][-5:]

     0   1   2   3
4   21  19  33  35
5   35  37  17  29
6   18  34  39  22
7   10  38  21  37
10  35  34  39  34

In [108]:
df

     0   1   2   3  sum
0   20  14  38  11   83
1   14  10  11  15   50
2   32  20  18  26   96
3   27  26  22  16   91
4   21  19  33  35  108
5   35  37  17  29  118
6   18  34  39  22  113
7   10  38  21  37  106
8   33  19  23  22   97
9   26  21  19  21   87
10  35  34  39  34  142
11  16  19  12  11   58
12  14  35  24  23   96
13  23  31  33  12   99
14  15  16  33  14   78

In [157]:
#23. How to find and cap outliers from a series or dataframe column?
ser = pd.Series(np.logspace(-2, 2, 30))
ser1 = ser.copy(deep = True)
ser2 = ser.copy(deep = True)

p5,p95=np.percentile(ser1,[5,95])

ser1DF=pd.DataFrame({'value':ser1})
ser1DF[(ser1DF['value']> p5) & (ser1DF['value']<p95)], p5, p95

(        value
 2    0.018874
 3    0.025929
 4    0.035622
 5    0.048939
 6    0.067234
 7    0.092367
 8    0.126896
 9    0.174333
 10   0.239503
 11   0.329034
 12   0.452035
 13   0.621017
 14   0.853168
 15   1.172102
 16   1.610262
 17   2.212216
 18   3.039195
 19   4.175319
 20   5.736153
 21   7.880463
 22  10.826367
 23  14.873521
 24  20.433597
 25  28.072162
 26  38.566204
 27  52.983169,
 0.016049294076965887,
 63.87667222018393)

In [58]:
x=np.random.randint(1,21,20)
print(x)
x1=pd.Series(x)
#pd.Series(x).plot()
[p5,p95]=np.percentile(x,[5,95])
print([p5,p95])
#print ([~x1.isin([p5,p95])])
#x2= x1[~x1.isin([p5,p95])]
x2=pd.DataFrame({'value':x})
print(x2)
mask=x[(x2['value']>p5) & (x2['value']<p95)]
mask

[11  1 15 18 13 12  2  3 18 12  5  2 20  9  3  6  9 10  2  9]
[1.9500000000000002, 18.1]
    value
0      11
1       1
2      15
3      18
4      13
5      12
6       2
7       3
8      18
9      12
10      5
11      2
12     20
13      9
14      3
15      6
16      9
17     10
18      2
19      9

array([11, 15, 18, 13, 12,  2,  3, 18, 12,  5,  2,  9,  3,  6,  9, 10,  2,
        9])

In [158]:
ser1DF['value'].sort_values(ascending=True)

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
5       0.048939
6       0.067234
7       0.092367
8       0.126896
9       0.174333
10      0.239503
11      0.329034
12      0.452035
13      0.621017
14      0.853168
15      1.172102
16      1.610262
17      2.212216
18      3.039195
19      4.175319
20      5.736153
21      7.880463
22     10.826367
23     14.873521
24     20.433597
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
Name: value, dtype: float64

In [96]:
#24. How to reverse the rows of a dataframe?
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df_r=df[::-1]
df_r, df.iloc[::-1,:]

(    0   1   2   3   4
 4  20  21  22  23  24
 3  15  16  17  18  19
 2  10  11  12  13  14
 1   5   6   7   8   9
 0   0   1   2   3   4,
     0   1   2   3   4
 4  20  21  22  23  24
 3  15  16  17  18  19
 2  10  11  12  13  14
 1   5   6   7   8   9
 0   0   1   2   3   4)

In [117]:
df

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [97]:
#21. How to filter every nth row in a dataframe?
#every 2nd row of df above

df.iloc[df.index%2==0,:]

    0   1   2   3   4
0   0   1   2   3   4
2  10  11  12  13  14
4  20  21  22  23  24

In [166]:
df.iloc[::2,:]

    0   1   2   3   4
0   0   1   2   3   4
2  10  11  12  13  14
4  20  21  22  23  24

In [122]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

In [123]:
df

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [127]:
#20. How to change the order of columns of a dataframe?
df.columns=['a','b','c','d','e']
col=['b','d','a','c','e']
df=df[col]
df

    b   d   a   c   e
0   1   3   0   2   4
1   6   8   5   7   9
2  11  13  10  12  14
3  16  18  15  17  19
4  21  23  20  22  24

In [60]:
#How to get teh count of missing values in a dataframe

d={'number': [1,5,3,np.nan,5], 'age':[12,15,np.nan,16,np.nan]}
d_df=pd.DataFrame(d)
d_df.isna().sum().sum(), d_df
d_df.isna(), d_df.isna().sum(), d_df.isna().sum().sum(), d_df

(   number    age
 0   False  False
 1   False  False
 2   False   True
 3    True  False
 4   False   True,
 number    1
 age       2
 dtype: int64,
 3,
    number   age
 0     1.0  12.0
 1     5.0  15.0
 2     3.0   NaN
 3     NaN  16.0
 4     5.0   NaN)

In [62]:
d_df_copy=d_df.copy()

In [63]:
d_df_copy.fillna(d_df_copy.mean(skipna=True), inplace=True)
d_df_copy

   number        age
0     1.0  12.000000
1     5.0  15.000000
2     3.0  14.333333
3     3.5  16.000000
4     5.0  14.333333

In [64]:
d_df_copy.fillna(np.nanmean(d_df_copy), inplace=True)
d_df_copy1=d_df_copy.apply(lambda x: round(x,2))
d_df_copy1, d_df_copy

(   number    age
 0     1.0  12.00
 1     5.0  15.00
 2     3.0  14.33
 3     3.5  16.00
 4     5.0  14.33,
    number        age
 0     1.0  12.000000
 1     5.0  15.000000
 2     3.0  14.333333
 3     3.5  16.000000
 4     5.0  14.333333)

In [68]:
d_df_copy

   number        age
0     1.0  12.000000
1     5.0  15.000000
2     3.0  14.333333
3     3.5  16.000000
4     5.0  14.333333

In [69]:
d_df['number'].mean(), d_df['age'].mean()

(3.5, 14.333333333333334)

In [100]:
#19. How to replace missing values of multiple numeric columns with the mean?

# d_df[["number"]]=d_df[["number"]].apply(lambda x: x.fillna(x.mean()))
# d_df[['age']]=d_df[['age']].apply(lambda x: x.fillna(x.mean()))
# d_df

d_df[['number']]=d_df[['number']].apply(lambda x: x.fillna(x.mean()))
d_df[['age']]=d_df[['age']].apply(lambda x:x.fillna(x.mean()))

In [67]:
d_df

   number        age
0     1.0  12.000000
1     5.0  15.000000
2     3.0  14.333333
3     3.5  16.000000
4     5.0  14.333333

In [85]:
#How to import only specified columns from a csv file
df=pd.read_csv("housing.csv", header=None,sep=",",usecols=["col1",'col2'])
df.head()

ValueError: Usecols do not match columns, columns expected but not found: ['col2', 'col1']

In [ ]:
#make sublist from a list like [[1, 2], [3, 4], [5, 6], [7, 8]]
l=[1,2,3,4,5,6,7,8,9] 
l2=[]
l2=[[x,x+1] for x in l if ((x%2==1) and (x+1 in l))]
l3=[item for sl in l2 for item in sl]
print(l, l2, l3)

l=[1,3,2,4,5,1,9,12,16,18]
l2=[[x,y] for x in l for y in l if (y==x**2 )]
l3=[]
[l3.append(x) for x in l2 if x not in l3]
l,l2,l3

[1, 2, 3, 4, 5, 6, 7, 8, 9] [[1, 2], [3, 4], [5, 6], [7, 8]] [1, 2, 3, 4, 5, 6, 7, 8]

([1, 3, 2, 4, 5, 1, 9, 12, 16, 18],
 [[1, 1], [1, 1], [3, 9], [2, 4], [4, 16], [1, 1], [1, 1]],
 [[1, 1], [3, 9], [2, 4], [4, 16]])

In [82]:
x1=[-1,-2,-3,0,1,2,4,0,3,5, -2 ] #1. get a unique list of tuples with the elements here and the resp squares like [(-1,1),(2,4)] etc 2. get a tuples like numbers and their resp squares like [(-1,1),(1,1),(1,1)]
sq=[[x,x**2] for x in x1]
sq1=[]
[sq1.append(x) for x in sq if x not in sq1]
sq1
items=[item for sq1 in sq for item in sq1]
np.unique([x for i,x in enumerate(items) if i%2==1]), items

(array([ 0,  1,  4,  9, 16, 25]),
 [-1, 1, -2, 4, -3, 9, 0, 0, 1, 1, 2, 4, 4, 16, 0, 0, 3, 9, 5, 25, -2, 4])

In [83]:
#Vishnu Kumaer (VK) we have to take VK from it. Using split function.
s= "Vishnu Kumaer"; l1=[x for x in list(s)]
n1=s.split(" ")[0][0]+s.split(" ")[1][0]
n1, " ".join(n1), " ".join(str(l)),l1, "".join(l1)

('VK',
 'V K',
 '[ 1 ,   3 ,   2 ,   4 ,   5 ,   1 ,   9 ,   1 2 ,   1 6 ,   1 8 ]',
 ['V', 'i', 's', 'h', 'n', 'u', ' ', 'K', 'u', 'm', 'a', 'e', 'r'],
 'Vishnu Kumaer')