In [5]:
import pandas as pd
import numpy as np

In [2]:
#1.Write a Pandas program to create a dataframe from a dictionary and display it.
Sample_data= {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

data_df=pd.DataFrame(Sample_data )
data_df.head()

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

In [6]:
#create df using index labels

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]

df=pd.DataFrame(exam_data, index=labels)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [16]:

df.describe(include='all')

             name      score   attempts qualify
count          10   8.000000  10.000000      10
unique         10        NaN        NaN       2
top     Anastasia        NaN        NaN     yes
freq            1        NaN        NaN       5
mean          NaN  13.562500   1.900000     NaN
std           NaN   4.693746   0.875595     NaN
min           NaN   8.000000   1.000000     NaN
25%           NaN   9.000000   1.000000     NaN
50%           NaN  13.500000   2.000000     NaN
75%           NaN  17.125000   2.750000     NaN
max           NaN  20.000000   3.000000     NaN

In [7]:
df.iloc[:3,:], df.loc[['a','b','c'],['name','score']]
df.iloc[:3,:],df.loc[['a','b'],['name','score']]

(        name  score  attempts qualify
 a  Anastasia   12.5         1     yes
 b       Dima    9.0         3      no
 c  Katherine   16.5         2     yes,
         name  score
 a  Anastasia   12.5
 b       Dima    9.0)

In [19]:
df['numbers']=df.index
df.rename(columns={'numbers':'letters'}, inplace=True)
df

        name  score  attempts qualify letters
a  Anastasia   12.5         1     yes       a
b       Dima    9.0         3      no       b
c  Katherine   16.5         2     yes       c
d      James    NaN         3      no       d
e      Emily    9.0         2      no       e
f    Michael   20.0         3     yes       f
g    Matthew   14.5         1     yes       g
h      Laura    NaN         1      no       h
i      Kevin    8.0         2      no       i
j      Jonas   19.0         1     yes       j

In [29]:
df.index
df.iloc[4,:]
type(df.loc[['d'],:])
type(df.loc['d',:])

pandas.core.series.Series

In [31]:
type(df.loc[:,:])

pandas.core.frame.DataFrame

In [33]:
df.set_index(df['letters'],inplace=True, drop=True)
#df.drop("index", axis=1, inplace=True)
df

              name  score  attempts qualify letters
letters
a        Anastasia   12.5         1     yes       a
b             Dima    9.0         3      no       b
c        Katherine   16.5         2     yes       c
d            James    NaN         3      no       d
e            Emily    9.0         2      no       e
f          Michael   20.0         3     yes       f
g          Matthew   14.5         1     yes       g
h            Laura    NaN         1      no       h
i            Kevin    8.0         2      no       i
j            Jonas   19.0         1     yes       j

In [34]:
df.drop("letters", axis=1, inplace=True)
#df.drop()
df

              name  score  attempts qualify
letters
a        Anastasia   12.5         1     yes
b             Dima    9.0         3      no
c        Katherine   16.5         2     yes
d            James    NaN         3      no
e            Emily    9.0         2      no
f          Michael   20.0         3     yes
g          Matthew   14.5         1     yes
h            Laura    NaN         1      no
i            Kevin    8.0         2      no
j            Jonas   19.0         1     yes

In [35]:
df.drop(['a','b'], axis=0, inplace=True)
df

              name  score  attempts qualify
letters
c        Katherine   16.5         2     yes
d            James    NaN         3      no
e            Emily    9.0         2      no
f          Michael   20.0         3     yes
g          Matthew   14.5         1     yes
h            Laura    NaN         1      no
i            Kevin    8.0         2      no
j            Jonas   19.0         1     yes

In [37]:
#Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.
#df.iloc[[1,3,5,6],:][['name','score']]
df.iloc[[1,3,5,6],:][['name','score']]

            name  score
letters
d          James    NaN
f        Michael   20.0
h          Laura    NaN
i          Kevin    8.0

In [80]:
df.iloc[[1,3,5,6],:][['name','score']]

          name  score
index
d        James    NaN
f      Michael   20.0
h        Laura    NaN
i        Kevin    8.0

In [81]:
df.loc[['d','f','h','i'],['name','score']]

          name  score
index
d        James    NaN
f      Michael   20.0
h        Laura    NaN
i        Kevin    8.0

In [8]:
#Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.
df[df['attempts']>2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [83]:
#Write a Pandas program to count the number of rows and columns of a DataFrame.
print("#rows = {}".format(df.shape[0]))
print("#cols = {}".format(df.shape[1]))

#rows = 8
#cols = 4

In [ ]:
#Write a Pandas program to select the rows where the score is missing, i.e. is NaN. ???
df[df['score'].isnull()]
df[~df['score'].isnull()], df[df['score'].isnull()]

(        name  score  attempts qualify
 a  Anastasia   12.5         1     yes
 b       Dima    9.0         3      no
 c  Katherine   16.5         2     yes
 e      Emily    9.0         2      no
 f    Michael   20.0         3     yes
 g    Matthew   14.5         1     yes
 i      Kevin    8.0         2      no
 j      Jonas   19.0         1     yes,
     name  score  attempts qualify
 d  James    NaN         3      no
 h  Laura    NaN         1      no)

In [85]:
#Write a Pandas program to select the rows the score is between 15 and 20 (inclusive). ???
df[(df['score']>=15) & (df['score']<=20)]

            name  score  attempts qualify
index
c      Katherine   16.5         2     yes
f        Michael   20.0         3     yes
j          Jonas   19.0         1     yes

In [86]:
#Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.
df[(df['attempts']<2) & (df['score']>15)]

        name  score  attempts qualify
index
j      Jonas   19.0         1     yes

In [87]:
#Write a Pandas program to change the score in row 'd' to 11.5.
df.loc['d','score']=11.5
df

            name  score  attempts qualify
index
c      Katherine   16.5         2     yes
d          James   11.5         3      no
e          Emily    9.0         2      no
f        Michael   20.0         3     yes
g        Matthew   14.5         1     yes
h          Laura    NaN         1      no
i          Kevin    8.0         2      no
j          Jonas   19.0         1     yes

In [88]:
#Write a Pandas program to calculate the sum of the examination attempts by the students.
df['attempts'].sum()

15

In [89]:
#Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.
np.nanmean(df['score'])

14.071428571428571

In [12]:
#Write a Pandas program to append a new row 'k' to data frame with given values for each column. Now delete the new row and return the original DataFrame.
new={'name' : "Suresh", 'score': 15.5, 'attempts': 1, 'qualify': "yes"} #, 'label': "k"} ???

df.loc['k']=new #['Suresh',15.5,1,'yes']
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

In [91]:
df.drop('k', inplace=True)
df

            name  score  attempts qualify
index
c      Katherine   16.5         2     yes
d          James   11.5         3      no
e          Emily    9.0         2      no
f        Michael   20.0         3     yes
g        Matthew   14.5         1     yes
h          Laura    NaN         1      no
i          Kevin    8.0         2      no
j          Jonas   19.0         1     yes

In [13]:
df.loc['k']=pd.Series(new)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

In [14]:
df.drop('k', inplace=True)
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [94]:
df.shape[0]

8

In [95]:
df.loc[df.shape[0],:]=new

df

            name  score  attempts qualify
index
c      Katherine   16.5       2.0     yes
d          James   11.5       3.0      no
e          Emily    9.0       2.0      no
f        Michael   20.0       3.0     yes
g        Matthew   14.5       1.0     yes
h          Laura    NaN       1.0      no
i          Kevin    8.0       2.0      no
j          Jonas   19.0       1.0     yes
8         Suresh   15.5       1.0     yes

In [15]:
df=df[:-1]
df

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no

In [45]:
df[::-1]

              name  score  attempts qualify
letters
h            Laura    NaN         1   False
g          Matthew   14.5         1    True
f          Michael   20.0         3    True
e            Emily    9.0         2   False
d            James    NaN         3   False
c        Katherine   16.5         2    True

In [46]:
df[::-2]

            name  score  attempts qualify
letters
h          Laura    NaN         1   False
f        Michael   20.0         3    True
d          James    NaN         3   False

In [47]:
df

              name  score  attempts qualify
letters
c        Katherine   16.5         2    True
d            James    NaN         3   False
e            Emily    9.0         2   False
f          Michael   20.0         3    True
g          Matthew   14.5         1    True
h            Laura    NaN         1   False

In [48]:
df[::-2]

            name  score  attempts qualify
letters
h          Laura    NaN         1   False
f        Michael   20.0         3    True
d          James    NaN         3   False

In [49]:
#Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.
df['qualify']=df['qualify'].str.replace('yes',"True").replace("no","False")
df['qualify']

/var/folders/88/96zsn82j511dx0zh7lxq70qm0000gn/T/ipykernel_6253/1137828289.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['qualify']=df['qualify'].str.replace('yes',"True").replace("no","False")

letters
c     True
d    False
e    False
f     True
g     True
h    False
Name: qualify, dtype: object

In [101]:
#Write a Pandas program to delete the 'attempts' column from the DataFrame.
df.drop(columns=['attempts'], axis=1, inplace=True)
df['Qu']=df['qualify'].apply(lambda x: (x[0].upper()))
df

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
<ipython-input-101-ae24ca94f20d>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Qu']=df['qualify'].apply(lambda x: (x[0].upper()))

            name  score qualify Qu
index
c      Katherine   16.5    True  T
d          James   11.5   False  F
e          Emily    9.0   False  F
f        Michael   20.0    True  T
g        Matthew   14.5    True  T
h          Laura    NaN   False  F
i          Kevin    8.0   False  F
j          Jonas   19.0    True  T

In [103]:
df

            name  score qualify Qu
index
c      Katherine   16.5    True  T
d          James   11.5   False  F
e          Emily    9.0   False  F
f        Michael   20.0    True  T
g        Matthew   14.5    True  T
h          Laura    NaN   False  F
i          Kevin    8.0   False  F
j          Jonas   19.0    True  T

In [104]:
#Write a Pandas program to insert a new column in existing DataFrame.
#df['attempts']=[1, 3, 2, 3, 2, 3, 1, 1, 2, 1]
attempt=[1, 3, 2, 3, 2, 3, 1, 1]
df.insert(2,"attempt",attempt)
df

            name  score  attempt qualify Qu
index
c      Katherine   16.5        1    True  T
d          James   11.5        3   False  F
e          Emily    9.0        2   False  F
f        Michael   20.0        3    True  T
g        Matthew   14.5        2    True  T
h          Laura    NaN        3   False  F
i          Kevin    8.0        1   False  F
j          Jonas   19.0        1    True  T

In [105]:
#Write a Pandas program to iterate over rows in a DataFrame.
for i, rows in df.iterrows():
    print (i,", ",rows)

c ,  name       Katherine
score           16.5
attempt            1
qualify         True
Qu                 T
Name: c, dtype: object
d ,  name       James
score       11.5
attempt        3
qualify    False
Qu             F
Name: d, dtype: object
e ,  name       Emily
score        9.0
attempt        2
qualify    False
Qu             F
Name: e, dtype: object
f ,  name       Michael
score         20.0
attempt          3
qualify       True
Qu               T
Name: f, dtype: object
g ,  name       Matthew
score         14.5
attempt          2
qualify       True
Qu               T
Name: g, dtype: object
h ,  name       Laura
score        NaN
attempt        3
qualify    False
Qu             F
Name: h, dtype: object
i ,  name       Kevin
score        8.0
attempt        1
qualify    False
Qu             F
Name: i, dtype: object
j ,  name       Jonas
score       19.0
attempt        1
qualify     True
Qu             T
Name: j, dtype: object

In [106]:
#Write a Pandas program to get list from DataFrame column headers.
list(df.columns)

['name', 'score', 'attempt', 'qualify', 'Qu']

In [108]:
cols=['attempt', 'name', 'qualify', "Qu",'score']
df=df[cols]
df

       attempt       name qualify Qu  score
index
c            1  Katherine    True  T   16.5
d            3      James   False  F   11.5
e            2      Emily   False  F    9.0
f            3    Michael    True  T   20.0
g            2    Matthew    True  T   14.5
h            3      Laura   False  F    NaN
i            1      Kevin   False  F    8.0
j            1      Jonas    True  T   19.0

In [109]:
#Rename cols of a df
d = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 4, 9]}
df1 = pd.DataFrame(d)
df1
#df.rename(columns={'col1':'Column1',"col2":"Column2","col3":"Column3"}, inplace=True)
df1.rename(columns={'col1':'Column1', 'col2':'Column2','col3':'Column3'}, inplace=True)
df1

   Column1  Column2  Column3
0        1        4        7
1        2        5        4
2        3        6        9

In [123]:
#Write a Pandas program to select rows from a given DataFrame based on values in some columns. say 4 ???

ind_l=[]
for i, rows in df1.iterrows():
    
    if 4 in list(rows):
        ind_l.append(i)

df1.loc[ind_l,:]

   Column1  Column2  Column3
0        1        4        7
1        2        5        4

In [67]:
#df to csv
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}
df = pd.DataFrame(d)
print("Original DataFrame")
print(df)
df.to_csv("df_to_csv_trial.csv", sep="\t")

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

In [50]:
#Write a Pandas program to count city wise number of people from a given of data set (city, name of the person).
df1 = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'city': ['California', 'Los Angeles', 'California', 'California', 'California', 'Los Angeles', 'Los Angeles', 'Georgia', 'Georgia', 'Los Angeles']})
df2=pd.DataFrame(df1.groupby("city")['name'].count()).reset_index()
df2
df3=pd.DataFrame(df1.groupby("city")['name'].apply(list))

df4=df1.groupby("city")['name'].apply(list).apply(lambda x :len(x))
df1, df2, df3, df4

(        name         city
 0  Anastasia   California
 1       Dima  Los Angeles
 2  Katherine   California
 3      James   California
 4      Emily   California
 5    Michael  Los Angeles
 6    Matthew  Los Angeles
 7      Laura      Georgia
 8      Kevin      Georgia
 9      Jonas  Los Angeles,
           city  name
 0   California     4
 1      Georgia     2
 2  Los Angeles     4,
                                              name
 city
 California   [Anastasia, Katherine, James, Emily]
 Georgia                            [Laura, Kevin]
 Los Angeles       [Dima, Michael, Matthew, Jonas],
 city
 California     4
 Georgia        2
 Los Angeles    4
 Name: name, dtype: int64)

In [55]:
df3=pd.DataFrame(df1.groupby("city")['name'].apply(list).apply(lambda x:len(x)))
df3

             name
city
California      4
Georgia         2
Los Angeles     4

In [131]:
#Write a Pandas program to delete DataFrame row(s) based on given column value. col2 != 5 ???
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
mask=df[df['col2']!=5].index
mask
df.loc[mask,:] #['col1']]

Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

   col1  col2  col3
0     1     4     7
2     3     6     9
3     4     7     0
4     5     8     1

In [81]:
#Write a Pandas program to widen output display to see more columns.

pd.set_option('display.max_columns', None)

In [82]:
#Write a Pandas program to select a row of series/dataframe by given integer index.
n=3
df.iloc[n,:]

col1    4
col2    7
col3    0
Name: 3, dtype: int64

In [133]:
#Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data)
print("Original DataFrame")
print(df)
df=df.fillna(0)
df

Original DataFrame
        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    0.0         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    0.0         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [134]:
#Write a Pandas program to set a given value for particular cell in  DataFrame using index value. index 8 score col by 10

df.loc[8,'score']=10.0
df

        name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    0.0         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    0.0         1      no
8      Kevin   10.0         2      no
9      Jonas   19.0         1     yes

In [56]:
#Write a Pandas program to divide a DataFrame in a given ratio say 70, 30 ???
df = pd.DataFrame(np.random.randn(10,2))
print("Original DataFrame:")
print(df)

part_70=df.sample(frac=0.7, random_state=10)
#part_70 = df.sample(frac=0.7,random_state=10)
part_30=df.drop(part_70.index)

#part_30 = df.drop(part_70.index)
print("\n70% of the said DataFrame:")
print(part_70)
print("\n30% of the said DataFrame:")
print(part_30)

Original DataFrame:
          0         1
0  0.732695 -1.465287
1  0.959984 -0.738500
2 -0.461753 -0.651492
3  0.443272  1.160589
4 -2.414826 -0.102310
5  1.934455 -0.210203
6 -0.303686  1.138807
7  0.456680 -1.479145
8 -1.241793 -0.148615
9 -0.691444 -0.777697

70% of the said DataFrame:
          0         1
8 -1.241793 -0.148615
2 -0.461753 -0.651492
5  1.934455 -0.210203
6 -0.303686  1.138807
3  0.443272  1.160589
1  0.959984 -0.738500
0  0.732695 -1.465287

30% of the said DataFrame:
          0         1
4 -2.414826 -0.102310
7  0.456680 -1.479145
9 -0.691444 -0.777697

In [115]:
#Write a Pandas program to shuffle a given DataFrame rows
df_shuffle=df.sample(frac=1, random_state=1)
df_shuffle

          0         1
2  0.062140 -0.542755
9 -0.330490 -0.943065
6 -0.569807  0.343483
4  0.479077 -1.285463
0  0.674030  0.513381
3  1.577954  0.435577
1 -1.330542 -0.353742
7 -1.051567 -0.890633
8  0.831476  1.146464
5 -0.559500 -0.329313

In [116]:
list(df[0]), type(df[0])

([0.6740295416389162,
  -1.330541561119966,
  0.06214007463498846,
  1.5779538589738245,
  0.4790772869206834,
  -0.5595002073062423,
  -0.5698070858712194,
  -1.051566807444263,
  0.8314764407096795,
  -0.33048953771510065],
 pandas.core.series.Series)

In [92]:
#Write a Pandas program to create a DataFrame from a Numpy array and specify the index column and column headers
data=np.arange(0,20).reshape(4,5)
d=np.arange(0,4)
df=pd.DataFrame(data, columns=['a','b','c','d','e'], index=d)
df

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [117]:
#Write a Pandas program to find the row for where the value of a given column is maximum. say col3
d = {'col1': [1, 2, 3, 4, 7], 'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}
df=pd.DataFrame(d)
df[df['col3']==df['col3'].max()], df

(   col1  col2  col3
 2     3     6    12,
    col1  col2  col3
 0     1     4     7
 1     2     5     8
 2     3     6    12
 3     4     9     1
 4     7     5    11)

In [119]:
mask=df[df['col3']==df['col3'].max()].index
mask
mask1=df[df['col3']==df['col3'].max()]
df.loc[mask,:]
print(mask1)
print( df.iloc[mask,:])

   col1  col2  col3
2     3     6    12
   col1  col2  col3
2     3     6    12

In [37]:
df

   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11

In [120]:
#df[df['col3']!=12] #or
df[~df['col3'].isin([12])]

   col1  col2  col3
0     1     4     7
1     2     5     8
3     4     9     1
4     7     5    11

In [96]:
#Write a Pandas program to check whether a given column is present in a DataFrame or not. say col4
if 'col4' in df.columns:
    print('col4'+" is a column in the df")
else:
    print('col4'+ " is not a column in the df")

col4 is not a column in the df

In [110]:
#Append another daata to an empty dataframe
df=pd.DataFrame()
data = pd.DataFrame({"col1": range(3),"col2": range(3)})
print("After appending some data:")
df = df.append(data)
print(df)

After appending some data:
   col1  col2
0     0     0
1     1     1
2     2     2

In [122]:
#Write a Pandas program to convert the datatype of a given column (floats to ints).
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"]

df=pd.DataFrame(exam_data, index=labels)
df['score']=df['score'].fillna(0).astype('int')
df['scores']=df[['score']].apply(lambda x: x.fillna(0)).astype('int')
df, df.dtypes

(        name  score  attempts qualify  scores
 a  Anastasia     12         1     yes      12
 b       Dima      9         3      no       9
 c  Katherine     16         2     yes      16
 d      James      0         3      no       0
 e      Emily      9         2      no       9
 f    Michael     20         3     yes      20
 g    Matthew     14         1     yes      14
 h      Laura      0         1      no       0
 i      Kevin      8         2      no       8
 j      Jonas     19         1     yes      19,
 name        object
 score        int64
 attempts     int64
 qualify     object
 scores       int64
 dtype: object)

In [247]:
import pandas as pd
import numpy as np
df = pd.DataFrame([1000, 2000, 3000, -4000, np.inf, -np.inf])
print("Original DataFrame:")
print(df)
print("Removing infinite values:")
df = df.replace([np.inf, -np.inf], np.nan) #??? replacing multiple things with one entity in one shot

print(df)

Original DataFrame:
        0
0  1000.0
1  2000.0
2  3000.0
3 -4000.0
4     inf
5    -inf
Removing infinite values:
        0
0  1000.0
1  2000.0
2  3000.0
3 -4000.0
4     NaN
5     NaN

In [57]:
#insert a new col at a specified index
d = {'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
new_col = [1, 2, 3, 4, 7]  
# insert the said column at the beginning in the DataFrame
idx = 0
#df.insert(idx,"new_col",new_col )
df.insert(0,"newCol",new_col)
df.rename(columns={'newCol':'Col'}, inplace=True)
df

Original DataFrame
   col2  col3
0     4     7
1     5     8
2     6    12
3     9     1
4     5    11

   Col  col2  col3
0    1     4     7
1    2     5     8
2    3     6    12
3    4     9     1
4    7     5    11

In [60]:
df[::-2]

   Col  col2  col3
4    7     5    11
2    3     6    12
0    1     4     7

In [157]:
#Write a Pandas program to convert a given list of lists into a Dataframe
ll=[[2, 4], [1, 3]]
ll_df=pd.DataFrame(ll, columns=["a",'b'])
ll_df, ll

(   a  b
 0  2  4
 1  1  3,
 [[2, 4], [1, 3]])

In [46]:
#Write a Pandas program to group by the first column and get second column as lists in rows.
df = pd.DataFrame( {'col1':['C1','C1','C2','C2','C2','C3','C2'], 'col2':[1,2,3,3,4,6,5]})
print("Original DataFrame")
print(df)
#df = df.groupby('col1')['col2'].apply(list)
df1 = pd.DataFrame(df.groupby('col1')['col2'].apply(list)) #??? 
df1

Original DataFrame
  col1  col2
0   C1     1
1   C1     2
2   C2     3
3   C2     3
4   C2     4
5   C3     6
6   C2     5

              col2
col1
C1          [1, 2]
C2    [3, 3, 4, 5]
C3             [6]

In [62]:
d = {'col1': [1, 2, 3, 4, 7], 'col2': [4, 5, 6, 9, 5], 'col3': [7, 8, 12, 1, 11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
print(list(df.columns).index('col2'))
l=[1,3,2,5]
l.index(2)

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
1

2

In [63]:
#Write a Pandas program to select all columns, except one given column in a DataFrame.
df.loc[:,df.columns!='col3']

   col1  col2
0     1     4
1     2     5
2     3     6
3     4     9
4     7     5

In [16]:
#Write a Pandas program to select all rows, except one given row in a DataFrame. say row 3 index
#df.loc[df.index!=3,:]
df.loc[df.index !=3,:], df[df.index !=3]

(        name  score  attempts qualify
 a  Anastasia   12.5         1     yes
 b       Dima    9.0         3      no
 c  Katherine   16.5         2     yes
 d      James    NaN         3      no
 e      Emily    9.0         2      no
 f    Michael   20.0         3     yes
 g    Matthew   14.5         1     yes
 h      Laura    NaN         1      no
 i      Kevin    8.0         2      no,
         name  score  attempts qualify
 a  Anastasia   12.5         1     yes
 b       Dima    9.0         3      no
 c  Katherine   16.5         2     yes
 d      James    NaN         3      no
 e      Emily    9.0         2      no
 f    Michael   20.0         3     yes
 g    Matthew   14.5         1     yes
 h      Laura    NaN         1      no
 i      Kevin    8.0         2      no)

In [145]:
df[:3], df[-3:] #first few and last few records

(   col1  col2  col3
 0     1     4     7
 1     2     5     8
 2     3     6    12,
    col1  col2  col3
 2     3     6    12
 3     4     9     1
 4     7     5    11)

In [161]:
df[:-3], df[-3:]

(   col1  col2  col3
 0     1     4     7
 1     2     5     8,
    col1  col2  col3
 2     3     6    12
 3     4     9     1
 4     7     5    11)

In [162]:
#topmost n records of groups in a df ???
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
print("\ntopmost n records within each group of a DataFrame:")
df1 = df.nlargest(3, 'col1')
df2=df.nlargest(3, 'col2')
df3=df.nlargest(3, 'col3')
df1,df2,df3

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

topmost n records within each group of a DataFrame:

(   col1  col2  col3
 5    11     0    11
 4     7     5     1
 3     4     9    12,
    col1  col2  col3
 3     4     9    12
 2     3     6     8
 1     2     5     5,
    col1  col2  col3
 3     4     9    12
 5    11     0    11
 2     3     6     8)

In [70]:
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
df

   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

In [68]:
#df1=df.sort_values(by='col1', ascending=False)[:3]
df1=df.sort_values(by='col1', ascending=False)[:3]
df2=df.sort_values(by='col2', ascending=False)[:3]
df3=df.sort_values(by='col3', ascending=False)[:3]
df1, df2, df3

(   col1  col2  col3
 5    11     0    11
 4     7     5     1
 3     4     9    12,
    col1  col2  col3
 3     4     9    12
 2     3     6     8
 1     2     5     5,
    col1  col2  col3
 3     4     9    12
 5    11     0    11
 2     3     6     8)

In [147]:
#Write a Pandas program to remove last n rows of a given DataFrame, say n=3
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
df_new=df[:(len(df)-3)]
df_new

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8

In [151]:
#Write a Pandas program to add a prefix or suffix to all columns of a given DataFrame. ???

dfcol= df.add_prefix("col_")
dfcol

   col_col1  col_col2  col_col3
0         1         4         7
1         2         5         5
2         3         6         8
3         4         9        12
4         7         5         1
5        11         0        11

In [71]:
#Write a Pandas program to select columns by data type of a given DataFrame. say float
df = pd.DataFrame({
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],
    'date_of_birth': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'age': [18.5, 21.2, 22.5, 22, 23]
})
df[df.columns[df.dtypes=='float64']]
#df[df.columns[df.dtypes=='float']]
df[df.columns[df.dtypes=='float']]

    age
0  18.5
1  21.2
2  22.5
3  22.0
4  23.0

In [163]:
# or
print(df.select_dtypes(include = "number"))

    age
0  18.5
1  21.2
2  22.5
3  22.0
4  23.0

In [167]:
#split df into 2 random subset sizes ???
df = pd.DataFrame({
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],
    'date_of_birth': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'age': ['18', '21', '22', '22', '23']
})
n=np.random.random()
print(round(n,2))
#first=df.sample(frac=np.round(n,2), random_state=10)
first=df.sample(frac=np.round(n,2), random_state=10)
#second=df.drop(first.index)
second=df.drop(first.index)
first,second

0.53

(             name date_of_birth age
 2     Ryan Parkes    25/09/1998  22
 3    Eesha Hinton    11/05/2002  22
 0  Alberto Franco    17/05/2002  18,
            name date_of_birth age
 1  Gino Mcneill    16/02/1999  21
 4  Syed Wharton    15/09/1997  23)

In [124]:
#Remove trailing (at the end) whitesapce and convert to lowercase of the columns names name date_of_birth age
df = pd.DataFrame({
    'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],
    'Date_Of_Birth ': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'Age': [18.5, 21.2, 22.5, 22, 23],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male']
})

print("Original DataFrame")
print(df)
df.columns = df.columns.str.lower().str.rstrip()
print(df)
df['name']=df['name'].apply(lambda x:((x.replace(" ","|").lower())))
c=df['name'].str.split("|", expand=True)
df2=pd.concat([df,c], axis=1)
df2.rename(columns={0:"FirstName",1:"LastName"}, inplace=True)
df2

Original DataFrame
             Name Date_Of_Birth    Age  Gender
0  Alberto Franco     17/05/2002  18.5    Male
1    Gino Mcneill     16/02/1999  21.2  Female
2     Ryan Parkes     25/09/1998  22.5    Male
3    Eesha Hinton     11/05/2002  22.0  Female
4    Syed Wharton     15/09/1997  23.0    Male
             name date_of_birth   age  gender
0  Alberto Franco    17/05/2002  18.5    Male
1    Gino Mcneill    16/02/1999  21.2  Female
2     Ryan Parkes    25/09/1998  22.5    Male
3    Eesha Hinton    11/05/2002  22.0  Female
4    Syed Wharton    15/09/1997  23.0    Male

             name date_of_birth   age  gender FirstName LastName
0  alberto|franco    17/05/2002  18.5    Male   alberto   franco
1    gino|mcneill    16/02/1999  21.2  Female      gino  mcneill
2     ryan|parkes    25/09/1998  22.5    Male      ryan   parkes
3    eesha|hinton    11/05/2002  22.0  Female     eesha   hinton
4    syed|wharton    15/09/1997  23.0    Male      syed  wharton

In [187]:
#df1=df.copy()

In [179]:
#Write a Pandas program to merge datasets and check uniqueness. ???

df = pd.DataFrame({
    'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],
    'Date_Of_Birth ': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'Age': [18.5, 21.2, 22.5, 22, 23]
})
print("Original DataFrame:")
print(df)
df1 = df.copy(deep = True)
df = df.drop([0, 1])
df1 = df1.drop([2])
print("\nNew DataFrames:")
print(df)
print(df1)
print('\n"one_to_one”: check if merge keys are unique in both left and right datasets:"')
df_one_to_one = pd.merge(df, df1, validate = "one_to_one")
print(df_one_to_one)
print('\n"one_to_many” or “1:m”: check if merge keys are unique in left dataset:')
df_one_to_many = pd.merge(df, df1, validate = "one_to_many")
print(df_one_to_many)
print('“many_to_one” or “m:1”: check if merge keys are unique in right dataset:')
df_many_to_one = pd.merge(df, df1, validate = "many_to_one")
print(df_many_to_one)

Original DataFrame:
             Name Date_Of_Birth    Age
0  Alberto Franco     17/05/2002  18.5
1    Gino Mcneill     16/02/1999  21.2
2     Ryan Parkes     25/09/1998  22.5
3    Eesha Hinton     11/05/2002  22.0
4    Syed Wharton     15/09/1997  23.0

New DataFrames:
           Name Date_Of_Birth    Age
2   Ryan Parkes     25/09/1998  22.5
3  Eesha Hinton     11/05/2002  22.0
4  Syed Wharton     15/09/1997  23.0
             Name Date_Of_Birth    Age
0  Alberto Franco     17/05/2002  18.5
1    Gino Mcneill     16/02/1999  21.2
3    Eesha Hinton     11/05/2002  22.0
4    Syed Wharton     15/09/1997  23.0

"one_to_one”: check if merge keys are unique in both left and right datasets:"
           Name Date_Of_Birth    Age
0  Eesha Hinton     11/05/2002  22.0
1  Syed Wharton     15/09/1997  23.0

"one_to_many” or “1:m”: check if merge keys are unique in left dataset:
           Name Date_Of_Birth    Age
0  Eesha Hinton     11/05/2002  22.0
1  Syed Wharton     15/09/1997  23.0
“many_to_one” or “m:1”: check if merge keys are unique in right dataset:
           Name Date_Of_Birth    Age
0  Eesha Hinton     11/05/2002  22.0
1  Syed Wharton     15/09/1997  23.0

In [72]:
#make a numerical col to a categorical col ???

df = pd.DataFrame({
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton', 'Kierra Gentry'],
      'age': [18, 22, 85, 50, 80, 5]
})
print("Original DataFrame:")
print(df)
print('\nAge group:')
#df["age_groups"]=pd.cut(df['age'], bins=[0,18,65,99], labels=["kids","adults","elderly"])
df['age_groups']=pd.cut(df['age'], bins=[0,18,65,99], labels=["kids","adults","elderly"])
#df["age_groups"] = pd.cut(df["age"], bins = [0, 18, 65, 99], labels = ["kids", "adult", "elderly"])
print(df["age_groups"])

Original DataFrame:
             name  age
0  Alberto Franco   18
1    Gino Mcneill   22
2     Ryan Parkes   85
3    Eesha Hinton   50
4    Syed Wharton   80
5   Kierra Gentry    5

Age group:
0       kids
1     adults
2    elderly
3     adults
4    elderly
5       kids
Name: age_groups, dtype: category
Categories (3, object): ['kids' < 'adults' < 'elderly']

In [51]:
df = pd.DataFrame({
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton', 'Kierra Gentry'],
      'age': [18, 22, 85, 50, 80, 5]
})
print("Original DataFrame:")
print(df)
print('\nAge group:')
df["age_groups"]=df["age"].astype(str)
df.dtypes, df

Original DataFrame:
             name  age
0  Alberto Franco   18
1    Gino Mcneill   22
2     Ryan Parkes   85
3    Eesha Hinton   50
4    Syed Wharton   80
5   Kierra Gentry    5

Age group:

(name          object
 age            int64
 age_groups    object
 dtype: object,
              name  age age_groups
 0  Alberto Franco   18         18
 1    Gino Mcneill   22         22
 2     Ryan Parkes   85         85
 3    Eesha Hinton   50         50
 4    Syed Wharton   80         80
 5   Kierra Gentry    5          5)

In [182]:
#display memory usage ???

import pandas as pd
df = pd.DataFrame({
    'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],
    'Date_Of_Birth ': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'Age': [18.5, 21.2, 22.5, 22, 23]
})
print("Original DataFrame:")
print(df)
print("\nGlobal usage of memory of the DataFrame:")
print(df.info(memory_usage = "deep"))
print("\nThe usage of memory of every column of the said DataFrame:")
print(df.memory_usage(deep = True))

Original DataFrame:
             Name Date_Of_Birth    Age
0  Alberto Franco     17/05/2002  18.5
1    Gino Mcneill     16/02/1999  21.2
2     Ryan Parkes     25/09/1998  22.5
3    Eesha Hinton     11/05/2002  22.0
4    Syed Wharton     15/09/1997  23.0

Global usage of memory of the DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            5 non-null      object
 1   Date_Of_Birth   5 non-null      object
 2   Age             5 non-null      float64
dtypes: float64(1), object(2)
memory usage: 849.0 bytes
None

The usage of memory of every column of the said DataFrame:
Index             128
Name              346
Date_Of_Birth     335
Age                40
dtype: int64

In [188]:
sr1 = pd.Series(['php', 'python', 'java', 'c#', 'c++'])
sr2 = pd.Series([1, 2, 3, 4, 5])
print("Original Series:")
print(sr1)
print(sr2)
print("Combine above series to a dataframe:")
ser_df = pd.DataFrame(sr1, sr2).reset_index()
print(ser_df.head())
print("\nUsing pandas concat:")
ser_df = pd.concat([sr1, sr2], axis = 1)
print(ser_df.head())
print("\nUsing pandas DataFrame with a dictionary, gives a specific name to the columns:")
ser_df = pd.DataFrame({"col1":sr1, "col2":sr2})
print(ser_df.head(5))

Original Series:
0       php
1    python
2      java
3        c#
4       c++
dtype: object
0    1
1    2
2    3
3    4
4    5
dtype: int64
Combine above series to a dataframe:
   index       0
0      1  python
1      2    java
2      3      c#
3      4     c++
4      5     NaN

Using pandas concat:
        0  1
0     php  1
1  python  2
2    java  3
3      c#  4
4     c++  5

Using pandas DataFrame with a dictionary, gives a specific name to the columns:
     col1  col2
0     php     1
1  python     2
2    java     3
3      c#     4
4     c++     5

In [189]:
import pandas as pd #???
print("DataFrame: Contains random values:")
df1 = pd.util.testing.makeDataFrame() # contains random values
print(df1)
print("\nDataFrame: Contains missing values:")
df2 = pd.util.testing.makeMissingDataframe() # contains missing values
print(df2)
print("\nDataFrame: Contains datetime values:")
df3 = pd.util.testing.makeTimeDataFrame() # contains datetime values
print(df3)
print("\nDataFrame: Contains mixed values:")
df4 = pd.util.testing.makeMixedDataFrame() # contains mixed values
print(df4)

DataFrame: Contains random values:
                   A         B         C         D
YgHBlQsFYB  0.820228  0.013464 -0.064979 -0.116969
SF5pPmFt4o  0.219978  0.107740 -1.585036  0.404327
PYc19r0rT6  0.022139 -0.164215 -0.275396  0.102502
JTYt4sLhTk  0.846773 -0.812367 -1.710142  0.282195
N4iYB9jr1L -0.338174  0.952181 -0.366941  1.188329
K0J2JyAxny  1.404047  0.624826  1.310933 -1.092952
nDzIlizETP  1.574374 -0.118391 -1.338378  0.171807
ep5OJGXZTK -0.001957  1.675190  1.073545 -0.992257
fahzyfjMKi  0.013360 -0.086315  0.915882 -0.398463
Vbamdd0lc1 -0.722264  0.503512  0.236210 -1.244218
jUGNZmTUBB  2.273517 -0.470110 -1.200420  0.200352
rnPmJB7z8l -0.114188 -0.483663 -0.606502 -0.335062
QfXrusnvSH -2.148461 -1.677133 -2.168879 -0.534790
BCGzPmJQO0  0.521982 -0.966719  0.577501  0.677720
NCIPYdmAjv  0.866419 -1.049970  0.000295  0.912655
C3FXU3fNcy  2.291322  1.537426 -0.714722  0.702803
rT1Bi8ONiZ  1.051450 -0.703615  0.414477  0.763485
mfKqrK3nqq  0.673446  0.367702  0.393160 -0.671524
lR2VwV6nud  2.791165 -0.232334 -0.775485  0.732348
PkpxAmVqEj -0.460027 -0.630935  0.400000  1.350800
rlc5zNrq4N  0.608942  1.009838  0.280643  0.181415
dvK1NKcAi9  0.670386  0.705443  0.588636  0.905456
K9laKP7fe3 -0.726143 -0.447168 -2.337336 -1.164769
d3vxuonpu9 -0.636069  2.007007  0.029539  0.195376
Dur8iEySDM -0.424965  0.477622 -1.325128  1.690128
u6L0Adp2UJ  0.407410  1.325714  0.268380 -0.339804
8rASDuZlxU  0.395740 -0.559936  0.587728 -0.858928
CvCORpQP6Q  1.344043 -0.661364  0.484313 -1.290470
aPZwNflDR3  1.543895  0.847382 -0.680204  1.403746
qa9betBmw7  0.298206  0.391612 -0.507236  0.326549

DataFrame: Contains missing values:
                   A         B         C         D
RpnW3wVUZ0 -0.867489 -0.088716  1.224802  0.957323
yB9ZjIOsKO       NaN -0.340937 -0.790985  0.271442
Q2AWZ3UCxh -0.510616       NaN -0.618450 -1.504329
oKaFCXK1rn -1.545737  0.022065 -0.496853  0.974828
AotRsOA93m -1.349702 -0.174899 -1.203210  1.164587
cPmEW5RToy  1.006750 -1.558071  0.293864  0.528247
rqNjIb6KnK -0.349446  2.119721       NaN -0.372545
1p7dmduDid  0.001686 -1.521706  0.233290 -0.483443
ew52R4v7ZZ -1.858430 -1.123222 -1.028309 -0.000316
vNISmG6Kk7 -1.428290  0.288634  0.895562 -0.239990
jcbmphuAOc -1.206169  0.851714 -0.046126 -1.826392
GEccC1gxle  1.238612 -0.125953  0.633875 -0.175356
rd7rthSLsC -1.936457  0.261815  0.938512  0.329311
CZN5I5SIFn  0.008806 -0.133944  0.664977  0.173339
2weZpWCKGd       NaN -1.273598 -0.322853 -0.416273
NFNnHlSqdS -0.492803 -0.860374 -0.462279  0.044309
ZEbAXyCD9b  2.770059  0.854323  0.650804  0.782144
Fxpk9QjVSr -1.275219  1.061028       NaN  0.195388
wl88nKCVFf  0.538586  0.663906 -0.272134       NaN
wGFaOngB1L -1.160693  0.448667  0.341624  0.813856
QH8QDV6UoF -0.147943 -1.655879 -1.274768       NaN
JCLYyuyulD -0.281042 -0.080182  0.370418  0.828727
8v8QaRinGB       NaN -0.331348  0.721294  0.022722
Kxib4mSbcv  0.301434 -0.704697 -1.065991  0.397751
m4W89HxlHj       NaN -0.249570  0.385224  0.591788
91B7Al7rVE       NaN  2.256126 -0.313886  0.061228
AJYR8hepWm  0.214582 -0.164069 -0.484193       NaN
zcls43bMsa -0.632599 -0.531948 -1.053879 -0.099101
mOVcYby8HN  0.616291 -0.432973  0.132845       NaN
ZDvTtCoIHY -1.437663 -0.422454  0.060676 -1.510515

DataFrame: Contains datetime values:
                   A         B         C         D
2000-01-03  3.251986  0.524924 -0.044809  0.421113
2000-01-04 -1.706190 -1.137758  3.427769 -2.086369
2000-01-05  1.125518  0.649176  2.715226  0.037705
2000-01-06  0.333744  0.170468  1.070404 -0.517709
2000-01-07  0.955862 -1.852072 -0.231934  0.515479
2000-01-10 -1.219449 -0.908941  0.127283 -2.042379
2000-01-11 -0.467771 -0.623076 -1.116216 -0.541998
2000-01-12 -0.577065  0.598864  1.838248  0.141120
2000-01-13  0.563764  1.257644 -0.395452  0.869750
2000-01-14 -2.658966 -0.066174 -0.690627 -0.169683
2000-01-17 -1.718462  0.799547  0.819696  1.320730
2000-01-18 -1.696887  0.575484 -0.589382  1.676744
2000-01-19  1.954619 -2.230728 -1.046610 -1.022085
2000-01-20 -1.577538  1.640529 -1.045605 -0.650924
2000-01-21 -2.072216  2.490624  0.090276  1.386866
2000-01-24  0.688998 -1.010859  0.434361 -0.451285
2000-01-25 -0.377519  1.422956 -0.312887 -2.378324
2000-01-26 -1.645998  0.123824  0.830653 -0.170180
2000-01-27 -0.666740  1.167149  0.599897 -1.850441
2000-01-28 -1.464653 -0.298246 -2.079157  0.351642
2000-01-31  1.349375  0.120880  1.159042 -1.250082
2000-02-01 -0.397417 -0.646418 -0.350828  1.787639
2000-02-02 -0.662233 -0.964987 -1.518196 -0.083965
2000-02-03 -0.112129  1.720944  1.366256  1.646653
2000-02-04 -0.501132 -0.313100  1.186900  0.239942
2000-02-07 -0.648658 -0.466555  1.075534  1.832730
2000-02-08  1.430489  0.804167  0.691683 -1.624383
2000-02-09 -2.180795 -1.042397  0.067070 -1.271340
2000-02-10  0.662967 -1.573496  1.776977  0.369388
2000-02-11 -0.448263  0.890950  0.497003  2.163461

DataFrame: Contains mixed values:
     A    B     C          D
0  0.0  0.0  foo1 2009-01-01
1  1.0  1.0  foo2 2009-01-02
2  2.0  0.0  foo3 2009-01-05
3  3.0  1.0  foo4 2009-01-06
4  4.0  0.0  foo5 2009-01-07

/opt/anaconda3/lib/python3.8/site-packages/pandas/util/__init__.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing

In [190]:
#fill missing values in datetime dataframe
sdata = {"c1":[120, 130 ,140, 150, np.nan, 170], "c2":[7, np.nan, 10, np.nan, 5.5, 16.5]}
df = pd.DataFrame(sdata)
df.index = pd.util.testing.makeDateIndex()[0:6]
print("Original DataFrame:")
print(df)
print("\nDataFrame after interpolate:")
print(df.interpolate())

Original DataFrame:
               c1    c2
2000-01-03  120.0   7.0
2000-01-04  130.0   NaN
2000-01-05  140.0  10.0
2000-01-06  150.0   NaN
2000-01-07    NaN   5.5
2000-01-10  170.0  16.5

DataFrame after interpolate:
               c1     c2
2000-01-03  120.0   7.00
2000-01-04  130.0   8.50
2000-01-05  140.0  10.00
2000-01-06  150.0   7.75
2000-01-07  160.0   5.50
2000-01-10  170.0  16.50

In [206]:
#Values which are less than maximum value of 'W' column ???

df = pd.DataFrame({'W':[68,75,86,80,66],'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print("Original DataFrame")
print(df)
M=df.W.max()
print(M)
df.query("W < @M")
df_LTMax=df[df['W']<df['W'].max()]
df_LTMax_ind=df[df['W']<df['W'].max()].index
df_GTMax=df.drop(df_LTMax_ind)
df_LTMax, df_GTMax, df.query("W < @M")

Original DataFrame
    W   X   Y   Z
0  68  78  84  86
1  75  85  94  97
2  86  96  89  96
3  80  80  83  72
4  66  86  86  83
86

(    W   X   Y   Z
 0  68  78  84  86
 1  75  85  94  97
 3  80  80  83  72
 4  66  86  86  83,
     W   X   Y   Z
 2  86  96  89  96,
     W   X   Y   Z
 0  68  78  84  86
 1  75  85  94  97
 3  80  80  83  72
 4  66  86  86  83)

In [52]:
#make uniform dtypes of purchase col string to float ???

d = {"agent": ["a001", "a002", "a003", "a003", "a004"], "purchase":[4500.00, 7500.00, "$3000.25", "$1250.35", "9000.00"]}
df = pd.DataFrame(d)
print("Original dataframe:")
print(df)
df['purchase']=df['purchase'].str.replace("[$,]","", regex=True).astype("float")
df['purchase']

Original dataframe:
  agent  purchase
0  a001    4500.0
1  a002    7500.0
2  a003  $3000.25
3  a003  $1250.35
4  a004   9000.00

0        NaN
1        NaN
2    3000.25
3    1250.35
4    9000.00
Name: purchase, dtype: float64

In [208]:
#check for the inequalities of the df #???
df1 = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,85,None,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
df2 = pd.DataFrame({'W':[78,75,86,80,None],'X':[78,85,96,80,76], 'Y':[84,84,89,83,86],'Z':[86,97,96,72,83]});
print("Original DataFrames:")
print(df1)
print(df2)
print("\nCheck for inequality of the said dataframes:")
print(df1.ne(df2))

Original DataFrames:
      W     X   Y   Z
0  68.0  78.0  84  86
1  75.0  85.0  94  97
2  86.0   NaN  89  96
3  80.0  80.0  83  72
4   NaN  86.0  86  83
      W   X   Y   Z
0  78.0  78  84  86
1  75.0  85  84  97
2  86.0  96  89  96
3  80.0  80  83  72
4   NaN  76  86  83

Check for inequality of the said dataframes:
       W      X      Y      Z
0   True  False  False  False
1  False  False   True  False
2  False   True  False  False
3  False  False  False  False
4   True   True  False  False

In [211]:
#Lowest n records within each group of a DataFrame: say n=3
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
Lcol1=df['col1'].sort_values()[:3]
Lcol2=df['col2'].sort_values()[:3]
Lcol3=df['col3'].sort_values()[:3]

Lcol1, Lcol2,Lcol3

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

(0    1
 1    2
 2    3
 Name: col1, dtype: int64,
 5    0
 0    4
 1    5
 Name: col2, dtype: int64,
 4    1
 1    5
 0    7
 Name: col3, dtype: int64)

In [214]:
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'], 
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'], 
        'marks': [201, 200, 198, 219, 201]})

print("Original DataFrames:")
print(student_data1)
print("-------------------------------------")
print(student_data2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([student_data1, student_data2], axis=0, ignore_index=True)
print(result_data)

Original DataFrames:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
-------------------------------------
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

Join the said two dataframes along rows:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
5         S4  Scarlette Fisher    201
6         S5  Carla Williamson    200
7         S6       Dante Morse    198
8         S7    Kaiser William    219
9         S8   Madeeha Preston    201

In [200]:
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'], 
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'], 
        'marks': [201, 200, 198, 219, 201]})

print("Original DataFrames:")
print(student_data1)
print("-------------------------------------")
print(student_data2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([student_data1, student_data2], axis=1, ignore_index=True)
print(result_data)

Original DataFrames:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
-------------------------------------
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

Join the said two dataframes along rows:
    0                 1    2   3                 4    5
0  S1  Danniella Fenton  200  S4  Scarlette Fisher  201
1  S2      Ryder Storey  210  S5  Carla Williamson  200
2  S3      Bryce Jensen  190  S6       Dante Morse  198
3  S4         Ed Bernal  222  S7    Kaiser William  219
4  S5       Kwame Morin  199  S8   Madeeha Preston  201

In [205]:
pd.merge(student_data1, student_data2, on=["student_id"]) #, how='inner')

  student_id       name_x  marks_x            name_y  marks_y
0         S4    Ed Bernal      222  Scarlette Fisher      201
1         S5  Kwame Morin      199  Carla Williamson      200

In [204]:
pd.merge(student_data1, student_data2, on=["student_id"], how='inner')

  student_id       name_x  marks_x            name_y  marks_y
0         S4    Ed Bernal      222  Scarlette Fisher      201
1         S5  Kwame Morin      199  Carla Williamson      200