In [3]:
def permute(nums):
    if len(nums) <= 1:
        return [nums]
    
    result = []
    for i, num in enumerate(nums):
        remaining_nums = nums[:i] + nums[i + 1:]
        for perm in permute(remaining_nums):
            result.append([num] + perm)
    
    return result

# Example usage:
array = [1, 2, 3]  # Replace this with your array of integers
result = permute(array)
print(result)
print(len(result))

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]
6

In [8]:
lis=[1,4,3,7,0]
lis[:0]+lis[0+1:]

[4, 3, 7, 0]

In [13]:
import numpy as np

In [15]:
#Recursive factorial
def fact(n):
    if n ==1 or  n==0:
        return 1
    else:
        return (n*fact(n-1))
    
n=5    
print("Factorial of %d is %d" % (n,fact(n)))

Factorial of 5 is 120

In [27]:
def checkprime(n):
    if n<0 :
        return (str(n)+" is a negative number")
    if not n<0 and (n==1 or n==0):
        return (str(n)+" is neither prime not composite")
    elif n>1:
         cnt=0
         for i in range(1,n//2):
                if n%i ==0:
                    cnt+=1
                
         if cnt==1:
                return (str(n)+" is a prime number")
         elif cnt>1:
                return (str(n)+" is not a prime number")
            
            
num=21
print (checkprime(num))

21 is not a prime number

In [28]:
#isprime one liner
import sympy as sp

sp.isprime(num)

False

In [20]:
#find median
ages=[5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31,52]
print(np.median(ages))
#[ages[(len(ages)+1//2)-1] if len(ages)%2==1 else (ages[len(ages)//2-1]+ages[(len(ages)//2)+1])/2]

31.5

[56.0]

In [37]:
import numpy as np
l= np.arange(5,1,-1)
l

array([5, 4, 3, 2])

In [40]:
def strRev(s):
    if len(s)==1:
        return s
    else:
        
        new_str=""
        for l in range(len(s)-1,-1, -1):
            #print(type(s[l]))
            new_str=new_str+s[l]
            
            
        return new_str
    
string="My new notebook"
print(strRev(string))

koobeton wen yM

In [42]:
print(string[::-1])

koobeton wen yM

In [102]:
import string
import pandas as pd
import numpy as np
from collections import Counter

def cntVowels(s):
    cnt=0
    s=s.lower()
    for l in s:
        if l in ['a', 'e','i','o','u']:
            cnt+=1
    return cnt
string="I love U too"
print(cntVowels(string))


val="".join(string.replace(" ",""))
print(val)
abc=[Counter(x) for x in list(string) if x.lower() in ['a', 'e','i','o','u']]
abc=[Counter(x) for x in list(string) if x.lower() in ['a', 'e','i','o','u']]
np.sum([x for a in abc for x in a.values()]), abc

6
IloveUtoo

(6,
 [Counter({'I': 1}),
  Counter({'o': 1}),
  Counter({'e': 1}),
  Counter({'U': 1}),
  Counter({'o': 1}),
  Counter({'o': 1})])

In [78]:
[Counter(x) for x in list(string) if x.lower() in ['a', 'e','i','o','u']]
list(string)

['I', ' ', 'l', 'o', 'v', 'e', ' ', 'U', ' ', 't', 'o', 'o']

In [22]:
#Min and Max from a list
def maxmin(l):
    if len(l)==1:
        M=l[0]
        m=l[0]
        return M,m
    else:
        M=l[0]
        m=l[0]
        for i in l:
            if i> M:
                M=i
            if i<m:
                m=i
                
        return M,m
    
lists=[4,4,6,100,2,-105, -105]

print("The max number is %d and min number is %d " %(maxmin(lists)))

The max number is 100 and min number is -105

In [42]:
print (np.max(lists))
print(np.min(lists))

100
-105

In [23]:
sorted(lists, key=lambda x:x, reverse=False)[0], sorted(lists, key=lambda x:x, reverse=False)[len(lists)-1]
sorted(lists,key=lambda x:x, reverse=False)[0], sorted(lists,key=lambda x:x, reverse=True)[0] #max and min

(-105, 100)

In [16]:
with open ("/Users/aswathy.n/Desktop/allFileNames.txt", "r") as F:

    lines=F.readlines()
    #lines_all=lines.join("")
    print (lines)
    cnt=0
    for l in lines:
        cnt+= len(l.split(" "))   
print (cnt)

['A01_A01_Sample_20201223_182440.fsa\n', 'A02_A02_Sample_20201223_182441.fsa\n', 'A02_C1-106HLA_B_2R_20201118_192205.ab1\n', 'A03_A03_Sample_20201223_182442.fsa\n', 'A03_C1-106HLA_B_3F_20201118_192206.ab1\n', 'A04_C1-106HLA_C_2R_20201119_095115.ab1\n', 'A04_TrueMark_S06-010363_Sample_20201112_143033.fsa\n', 'A04_TrueMark_S06-010363_Sample_20201112_194117.fsa\n', 'A04_TrueMark_S06-010363_Sample_20201112_225639.fsa\n', 'A04_TrueMark_S06-010363_Sample_20201113_025100.fsa\n', 'A05_C1-106HLA_C_3F_20201119_095116.ab1\n', 'A06_C1-106HLA_C_3R_20201119_095117.ab1\n', 'A08_C1-106HLA_C_4R_20201119_105230.ab1\n', 'A10_C1-106HLA_C_5R_20201119_115342.ab1\n', 'B02_C1-107HLA_B_2R_20201118_192208.ab1\n', 'B03_C1-107HLA_B_3F_20201118_192209.ab1\n', 'B04_C1-107HLA_C_2R_20201119_095118.ab1\n', 'B04_TrueMark_3435(1420)T_Sample_20201112_143036.fsa\n', 'B04_TrueMark_3435(1420)T_Sample_20201112_162600.fsa\n', 'B04_TrueMark_3435(1420)T_Sample_20201112_202023.fsa\n', 'B04_TrueMark_3435(1420)T_Sample_20201113_075104.fsa\n', 'B04_TrueMark_3435(1420)T_Sample_20201113_094212.fsa\n', 'B05_C1-107HLA_C_3F_20201119_095119.ab1\n', 'B05_TrueMark_S06-012578_Sample_20201112_221738.fsa\n', 'B05_TrueMark_S06-012578_Sample_20201113_021200.fsa\n', 'B05_TrueMark_S06-012578_Sample_20201113_064522.fsa\n', 'B05_TrueMark_S06-012578_Sample_20201113_101927.fsa\n', 'B06_C1-107HLA_A_3R_20201118_161833.ab1\n', 'B07_C1-107HLA_C_4F_20201119_105232.ab1\n', 'B08_C1-107HLA_A_4R_20201118_171944.ab1\n', 'B08_C1-107HLA_C_4R_20201119_105233.ab1\n', 'B11_C1-107HLA_C_6F_20201119_115346.ab1\n', 'BDDpUC19_BDXFstSeq50POP7_RT_B01_2_20210630_125633.ab1\n', 'BDDpUC19_BDXFstSeq50POP7_RT_B01_2_20210630_125633.ab1\n', 'BDDpUC19_BDXFstSeq50POP7_RT_E02_14_20210625_203531.ab1\n', 'BDDpUC19_BDXFstSeq50POP7_RT_E02_14_20210625_203531.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_A01_1_20210625_185543.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_C02_8_20210625_231638.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_C02_8_20210625_231638.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_D02_11_20210625_231641.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_D03_12_20210625_223912.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_D03_12_20210625_223912.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_D03_12_20210625_231642.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_D03_12_20210625_231642.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_E02_14_20210625_231644.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_E03_15_20210625_231645.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_E03_15_20210625_231645.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_F01_16_20210625_231646.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_F01_16_20210625_231646.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_F02_17_20210625_231647.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_F03_18_20210625_231648.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_H02_23_20210625_231653.ab1\n', 'BDDpUC19_BDXRpdSeq50POP7_RT_H02_23_20210625_231653.ab1\n', 'BDDpUC19_BDXStdSeq50POP7_RT_E02_14_20210625_163043.ab1\n', 'BDDpUC19_BDXStdSeq50POP7_RT_E02_14_20210625_163043.ab1\n', 'BDDpUC19_RpdSeq50POP7_15C20RH_C02_8_20210625_160705.ab1\n', 'BDDpUC19_RpdSeq50POP7_15C20RH_D02_11_20210625_165855.ab1\n', 'BDDpUC19_RpdSeq50POP7_30C80RH_H02_23_20210729_154716.ab1\n', 'BDDpUC19_RpdSeq50POP7_RT_C03_9_20210628_113355.ab1\n', 'BDDpUC19_RpdSeq50POP7_RT_D03_12_20210628_113358.ab1\n', 'BDDpUC19_RpdSeq50POP7_RT_E02_14_20210628_113400.ab1\n', 'BDDpUC19_RpdSeq50POP7_RT_E02_14_20210628_121814.ab1\n', 'BDDpUC19_RpdSeq50POP7_RT_E03_15_20210628_113401.ab1\n', 'BDDpUC19_RpdSeq50POP7_RT_F02_17_20210628_113403.ab1\n', 'BDDpUC19_RpdSeq50POP7_RT_F03_18_20210628_113404.ab1\n', 'BDDpUC19_RpdSeq50POP7_RT_G01_19_20210628_113405.ab1\n', 'BDDpUC19_RpdSeq50POP7_RT_G03_21_20210628_113407.ab1\n', 'BDDpUC19_RpdSeq50POP7_RT_H02_23_20210628_113409.ab1\n', 'BDT1.1_BDXFstSeq50POP7_RT_A03_3_20210628_162552.ab1\n', 'BDT1.1_BDXFstSeq50POP7_RT_F01_6_20210629_162446.ab1\n', 'BDT1.1_BDXRpd36POP7_RT_C09_9_20210625_140407.ab1\n', 'BDT1.1_BDXRpdSeq50POP6_RT_F02_17_20210630_152501.ab1\n', 'BDT1.1_BDXRpdSeq50POP6_RT_G01_19_20210630_152503.ab1\n', 'BDT1.1_BDXSRSeq50POP7_RT_E03_15_20210624_141922.ab1\n', 'BDT1.1_FST50POP7_15C20RH_C01_7_20210621_161130.ab1\n', 'BDT1.1_FST50POP7_15C20RH_G02_20_20210621_161143.ab1\n', 'BDT1.1_FstSeq36POP7_RT_C04_7_20210623_201732.ab1\n', 'BDT1.1_FstSeq36POP7_RT_E01_5_20210623_170133.ab1\n', 'BDT1.1_FstSeq50POP6_15C20RH_D05_11_20210622_000921.ab1\n', 'BDT1.1_FstSeq50POP6_30C80RH_A02_1_20210802_131126.ab1\n', 'BDT1.1_FstSeq50POP6_RT_E01_5_20210617_165257.ab1\n', 'BDT1.1_FstSeq50POP7_30C80RH_B02_5_20210725_140253.ab1\n', 'BDT1.1_FstSeq50POP7_30C80RH_C01_3_20210725_154808.ab1\n', 'BDT1.1_FstSeq50POP7_30C80RH_C02_8_20210725_125945.ab1\n', 'BDT1.1_MSeqID50POP6_15C20RH_C04_7_20210618_172630.ab1\n', 'BDT1.1_MSeqID50POP6_15C20RH_E04_13_20210618_151648.ab1\n', 'BDT1.1_MSeqID50POP6_15C20RH_H05_23_20210618_151658.ab1\n', 'BDT1.1_MSeqID50POP6_30C80RH_D02_11_20210725_130041.ab1\n', 'BDT1.1_MSeqID50POP6_30C80RH_G03_21_20210725_130051.ab1\n', 'BDT1.1_MSeqID50POP6_30C80RH_H02_23_20210725_130053.ab1\n', 'BDT1.1_MSeqID50POP6_RT_D01_4_20210621_215036.ab1\n', 'BDT1.1_RpdSeq30POP6_30C80RH_H01_8_20210803_153012.ab1\n', 'BDT1.1_RpdSeq36P0P7_RT_D03_12_20210630_161002.ab1\n', 'BDT1.1_RpdSeq36POP4_15C20RH_E01_13_20210624_122335.ab1\n', 'BDT1.1_RpdSeq36POP4_15C20RH_H01_22_20210624_122344.ab1\n', 'BDT1.1_RpdSeq36POP4_30C80RH_B06_6_20210803_161125.ab1\n', 'BDT1.1_RpdSeq36POP4_30C80RH_C04_7_20210803_161126.ab1\n', 'BDT1.1_RpdSeq36POP6_15C20RH_D04_10_20210623_020322.ab1\n', 'BDT1.1_RpdSeq36POP6_30C80RH_B05_5_20210802_133735.ab1\n', 'BDT1.1_RpdSeq36POP6_RT_A01_1_20210622_100329.ab1\n', 'BDT1.1_RpdSeq36POP7_RT_A05_2_20210624_124813.ab1\n', 'BDT1.1_RpdSeq50POP6_15C20RH_E04_13_20210621_153852.ab1\n', 'BDT1.1_RpdSeq50POP6_RT_D01_4_20210621_152032.ab1\n', 'BDT1.1_StdSeq50POP6_15C20RH_B04_4_20210617_212446.ab1\n', 'BDT1.1_StdSeq50POP6_15C20RH_G06_21_20210617_212503.ab1\n', 'BDT1.1_StdSeq50POP7_15C20RH_A03_3_20210617_120317.ab1\n', 'BDT1.1_StdSeq50POP7_30C80RH_A01_1_20210724_114753.ab1\n', 'BDT1.1_StdSeq50POP7_RT_H02_23_20210621_180011.ab1\n', 'BDT3.1_BDXFstSeq50POP7_RT_C04_7_20210628_172750.ab1\n', 'BDT3.1_BDXFstSeq50POP7_RT_F04_16_20210628_172759.ab1\n', 'BDT3.1_BDXRpdSeq50POP7_RT_A02_1_20210629_154455.ab1\n', 'BDT3.1_BDXRpdSeq50POP7_RT_E05_14_20210624_131019.ab1\n', 'BDT3.1_BDXSRSeq50POP7_RT_B02_2_20210706_133644.ab1\n', 'BDT3.1_BDXSRSeq50POP7_RT_C05_8_20210624_151909.ab1\n', 'BDT3.1_BDXSRSeq50POP7_RT_D06_12_20210624_151913.ab1\n', 'BDT3.1_BDXSRSeq50POP7_RT_F02_6_20210706_133648.ab1\n', 'BDT3.1_BDXSRSeq50POP7_RT_G04_19_20210624_151920.ab1\n', 'BDT3.1_BDXSRSeq50POP7_RT_H02_8_20210706_133650.ab1\n', 'BDT3.1_FstSeq36POP7_15C20RH_E06_15_20210623_153418.ab1\n', 'BDT3.1_FstSeq36POP7_RT_C01_7_20210713_095814.ab1\n', 'BDT3.1_FstSeq36POP7_RT_D08_11_20210623_211437.ab1\n', 'BDT3.1_FstSeq36POP7_RT_F01_16_20210713_095823.ab1\n', 'BDT3.1_FstSeq36POP7_RT_F01_16_20210713_110912.ab1\n', 'BDT3.1_FstSeq50POP6_15C20RH_B07_4_20210622_013438.ab1\n', 'BDT3.1_FstSeq50POP6_15C20RH_F09_18_20210622_013452.ab1\n', 'BDT3.1_FstSeq50POP6_30C80RH_E03_5_20210802_173014.ab1\n', 'BDT3.1_FstSeq50POP7_30C80RH_C04_7_20210725_150410.ab1\n', 'BDT3.1_FstSeq50POP7_30C80RH_E02_5_20210725_164212.ab1\n', 'BDT3.1_FstSeq50POP7_30C80RH_E02_5_20210725_175139.ab1\n', 'BDT3.1_FstSeq50POP7_30C80RH_E05_14_20210725_150417.ab1\n', 'BDT3.1_FstSeq50POP7_30C80RH_H06_24_20210725_160542.ab1\n', 'BDT3.1_FstSeq50POP7_RT_C06_9_20210622_182649.ab1\n', 'BDT3.1_FstSeq50POP7_RT_D04_10_20210622_192739.ab1\n', 'BDT3.1_FstSeq50POP7_RT_E05_14_20210622_192743.ab1\n', 'BDT3.1_FstSeq50POP7_RT_G05_20_20210622_182700.ab1\n', 'BDT3.1_RpdSeq36POP6_RT_D02_4_20210622_132103.ab1\n', 'BDT3.1_RpdSeq36POP6_RT_D05_11_20210622_135851.ab1\n', 'BDT3.1_RpdSeq36POP6_RT_E05_14_20210617_192100.ab1\n', 'BDT3.1_RpdSeq36POP6_RT_G04_19_20210617_192105.ab1\n', 'BDT3.1_RpdSeq36POP7_RT_C07_7_20210624_142126.ab1\n', 'BDT3.1_RpdSeq50POP6_15C20RH_C08_8_20210621_185011.ab1\n', 'BDT3.1_RpdSeq50POP6_15C20RH_G07_19_20210621_174634.ab1\n', 'BDT3.1_RpdSeq50POP6_15C20RH_H09_24_20210621_185027.ab1\n', 'BDT3.1_RpdSeq50POP6_RT_B04_4_20210621_201546.ab1\n', 'BDT3.1_RpdSeq50POP6_RT_F04_16_20210621_201558.ab1\n', 'BDT3.1_StdSeq50POP7_15C20RH_C05_8_20210617_162014.ab1\n', 'BDT3.1_StdSeq50POP7_15C20RH_E04_13_20210617_162019.ab1\n', 'BDT3.1_StdSeq50POP7_RT_E05_14_20210622_001431.ab1\n', 'BVMM1000_FA50POP7_15C20RH_B03_6_20210616_142426.fsa\n', 'BVMM1000_FA50POP7_15C20RH_C01_7_20210616_145435.fsa\n', 'BVMM1000_FA50POP7_15C20RH_E04_13_20210616_161449.fsa\n', 'BVMM1000_FA50POP7_15C20RH_F03_18_20210616_105241.fsa\n', 'BVMM1000_FA50POP7_30C80RH_B05_5_20210720_195131.fsa\n', 'BVMM1000_FA50POP7_30C80RH_D03_12_20210720_145520.fsa\n', 'BVMM1000_FA50POP7_30C80RH_D04_10_20210720_161225.fsa\n', 'BVMM1000_FA50POP7_30C80RH_H02_23_20210720_145522.fsa\n', 'BVMM1000_FA50POP7_30C80RH_H02_8_20210720_161243.fsa\n', 'BVMM1000_FA50POP7_RT_A02_2_20210616_111152.fsa\n', 'BVMM1000_FA50POP7_RT_D01_10_20210616_130725.fsa\n', 'BVMM1000_FA50POP7_RT_D01_10_20210616_145406.fsa\n', 'BVMM1000_FA50POP7_RT_D05_11_20210616_161401.fsa\n', 'BVMM1000_FA50POP7_RT_E01_13_20210616_134600.fsa\n', 'BVMM1000_FA50POP7_RT_F02_17_20210616_121431.fsa\n', 'BVMM1250_LFA50POP7_15C20RH_A02_1_20210610_155635.fsa\n', 'BVMM1250_LFA50POP7_15C20RH_A06_3_20210610_153313.fsa\n', 'BVMM1250_LFA50POP7_15C20RH_B02_5_20210610_112752.fsa\n', 'BVMM1250_LFA50POP7_15C20RH_D01_4_20210611_092147.fsa\n', 'BVMM1250_LFA50POP7_15C20RH_E01_13_20210610_173843.fsa\n', 'BVMM1250_LFA50POP7_15C20RH_E01_5_20210610_112839.fsa\n', 'BVMM1250_LFA50POP7_15C20RH_F01_6_20210611_092149.fsa\n', 'BVMM1250_LFA50POP7_15C20RH_G02_20_20210610_173540.fsa\n', 'BVMM1250_LFA50POP7_15C20RH_H02_8_20210610_153228.fsa\n', 'BVMM1250_LFA50POP7_30C80RH_B01_2_20210721_114400.fsa\n', 'BVMM1250_LFA50POP7_30C80RH_B02_5_20210718_165459.fsa\n', 'BVMM1250_LFA50POP7_30C80RH_B02_5_20210721_114437.fsa\n', 'BVMM1250_LFA50POP7_30C80RH_B02_5_20210721_175141.fsa\n', 'BVMM1250_LFA50POP7_30C80RH_C02_8_20210721_114440.fsa\n', 'BVMM1250_LFA50POP7_30C80RH_C02_8_20210721_134658.fsa\n', 'BVMM1250_LFA50POP7_30C80RH_G01_19_20210718_165513.fsa\n', 'BVMM1250_LFA50POP7_30C80RH_G06_21_20210718_205403.fsa\n', 'BVMM1250_LFA50POP7_30C80RH_H01_22_20210721_114454.fsa\n', 'BVMM1250_LFA50POP7_30C80RH_H01_22_20210721_155055.fsa\n', 'BVMM1250_LFA50POP7_RT_B06_6_20210610_212128.fsa\n', 'BVMM1250_LFA50POP7_RT_C06_9_20210610_131247.fsa\n', 'BVMM1250_LFA50POP7_RT_E09_15_20210611_014125.fsa\n', 'BVMM1250_LFA50POP7_RT_F09_18_20210611_014128.fsa\n', 'BVMM1250_LFA50POP7_RT_H04_22_20210610_212144.fsa\n', 'BVMM1250_LFA50POP7_RT_H06_24_20210610_233819.fsa\n', 'C01_C1-108HLA_C_1F_20201119_084941.ab1\n', 'C02_C1-108HLA_B_2R_20201118_192211.ab1\n', 'C02_C1-108HLA_C_1R_20201119_084942.ab1\n', 'C03_C1-108HLA_B_3F_20201118_192212.ab1\n', 'C03_C1-108HLA_C_2F_20201119_084943.ab1\n', 'C05_TrueMark_S07-025066_Sample_20201112_233549.fsa\n', 'C05_TrueMark_S07-025066_Sample_20201113_060622.fsa\n', 'C05_TrueMark_S07-025066_Sample_20201113_064525.fsa\n', 'C06_C1-108HLA_C_3R_20201119_095123.ab1\n', 'C07_C1-108HLA_C_4F_20201119_105235.ab1\n', 'C08_C1-108HLA_C_4R_20201119_105236.ab1\n', 'D03_C1-115HLA_C_2F_20201119_084946.ab1\n', 'D04_TrueMark_S08-021103_Sample_20201112_170512.fsa\n', 'D05_TrueMark_Control-1_Sample_20201112_150759.fsa\n', 'D05_TrueMark_Control-1_Sample_20201112_235004.fsa\n', 'D05_TrueMark_Control-1_Sample_20201113_005358.fsa\n', 'D05_TrueMark_Control-1_Sample_20201113_025110.fsa\n', 'D05_TrueMark_Control-1_Sample_20201113_040858.fsa\n', 'D07_C1-115HLA_C_4F_20201119_105238.ab1\n', 'D10_C1-115HLA_C_5R_20201119_115351.ab1\n', 'DS33IS_FA36POP4_15C20RH_A02_2_20210628_123003.fsa\n', 'DS33IS_FA36POP4_15C20RH_A03_3_20210614_154347.fsa\n', 'DS33IS_FA36POP4_20210615_E05_14_20210615_112827.fsa\n', 'DS33IS_FA36POP4_20210615_F06_18_20210621_121208.fsa\n', 'DS33IS_FA36POP4_20210615_G06_21_20210615_161858.fsa\n', 'DS33IS_FA36POP4_30C80RH_A01_1_20210719_213005.fsa\n', 'DS33IS_FA36POP4_30C80RH_A01_1_20210720_001301.fsa\n', 'DS33IS_FA36POP4_30C80RH_B03_6_20210719_202559.fsa\n', 'DS33IS_FA36POP4_30C80RH_B03_6_20210720_001306.fsa\n', 'DS33IS_FA36POP4_30C80RH_D02_11_20210719_213015.fsa\n', 'DS33IS_FA36POP4_30C80RH_D02_4_20210719_220229.fsa\n', 'DS33IS_FA36POP4_30C80RH_D04_10_20210719_221339.fsa\n', 'DS33IS_FA36POP4_30C80RH_E01_13_20210719_224629.fsa\n', 'DS33IS_FA36POP4_30C80RH_E03_15_20210719_235206.fsa\n', 'DS33IS_FA36POP4_30C80RH_E03_15_20210720_001315.fsa\n', 'DS33IS_FA36POP4_30C80RH_F05_17_20210720_004554.fsa\n', 'DS33IS_FA36POP4_30C80RH_G05_20_20210720_011830.fsa\n', 'DS33IS_FA36POP4_30C80RH_H06_24_20210720_011834.fsa\n', 'DS33IS_FA36POP4_RT_A04_1_20210615_113517.fsa\n', 'DS33IS_FA36POP4_RT_B06_6_20210615_113522.fsa\n', 'DS33IS_FA36POP4_RT_B06_6_20210809_140951.fsa\n', 'DS33IS_FA36POP4_RT_C03_9_20210615_140736.fsa\n', 'DS33IS_FA36POP4_RT_C03_9_20210615_151140.fsa\n', 'DS33IS_FA36POP4_RT_D03_12_20210615_144105.fsa\n', 'DS33IS_FA36POP4_RT_D06_12_20210615_113528.fsa\n', 'DS33IS_FA36POP4_RT_E02_14_20210809_133728.fsa\n', 'DS33IS_FA36POP4_RT_F02_17_20210615_140909.fsa\n', 'DS33IS_FA36POP4_RT_F03_18_20210621_114227.fsa\n', 'DS33IS_FA36POP4_RT_F04_16_20210615_113532.fsa\n', 'DS33IS_FA36POP4_RT_F05_17_20210614_121435.fsa\n', 'DS33IS_FA36POP4_RT_H04_22_20210614_124706.fsa\n', 'DS33IS_FA36POP4_RT_H06_24_20210615_154425.fsa\n', 'DS33IS_FA36POP6_30C80RH_B02_2_20210803_131726.fsa\n', 'DS33IS_FA36POP6_30C80RH_C04_7_20210719_175352.fsa\n', 'DS33IS_FA36POP6_30C80RH_F01_16_20210719_143647.fsa\n', 'DS33IS_FA36POP6_30C80RH_G02_20_20210719_143651.fsa\n', 'DS33IS_FA36POP7_15C20RH_D04_10_20210609_121741.fsa\n', 'DS33IS_FA36POP7_30C80RH_F01_6_20210723_101236.fsa\n', 'DS33IS_FA36POP7_RT_C01_7_20210609_100426.fsa\n', 'DS33IS_FA36POP7_RT_E02_5_20210609_110347.fsa\n', 'E01_C1-116HLA_C_1F_20201119_084947.ab1\n', 'E01_E01_Sample_20201223_182452.fsa\n', 'E02_E02_Sample_20201223_182453.fsa\n', 'E03_C1-116HLA_B_3F_20201118_192218.ab1\n', 'E03_C1-116HLA_C_2F_20201119_084949.ab1\n', 'E03_E03_Sample_20201223_182454.fsa\n', 'E04_C1-116HLA_C_2R_20201119_095127.ab1\n', 'E06_C1-116HLA_A_3R_20201118_161842.ab1\n', 'E06_C1-116HLA_C_3R_20201119_095129.ab1\n', 'E11_C1-116HLA_C_6F_20201119_115355.ab1\n', 'F01_C1-122HLA_A_1F_20201118_151730.ab1\n', 'F01_C1-122HLA_C_1F_20201119_084950.ab1\n', 'F04_TrueMark_S07-001490_Sample_20201112_194132.fsa\n', 'F04_TrueMark_S07-001490_Sample_20201112_205940.fsa\n', 'F04_TrueMark_S07-001490_Sample_20201113_040921.fsa\n', 'G02_C1-123HLA_B_2R_20201118_192223.ab1\n', 'G03_C1-123HLA_B_3F_20201118_192224.ab1\n', 'G03_C1-123HLA_C_2F_20201119_084955.ab1\n', 'G04_C1-123HLA_B_3R_20201118_202337.ab1\n', 'G04_TrueMark_S08-021103_Sample_20201113_001503.fsa\n', 'G04_TrueMark_S08-021103_Sample_20201113_033204.fsa\n', 'G04_TrueMark_S08-021103_Sample_20201113_064536.fsa\n', 'G04_TrueMark_S08-021103_Sample_20201113_072440.fsa\n', 'G04_TrueMark_S08-021103_Sample_20201113_094217.fsa\n', 'G05_TrueMark_CEPH-10_Sample_20201112_205944.fsa\n', 'G05_TrueMark_CEPH-10_Sample_20201113_040901.fsa\n', 'G06_TrueMark_CEPH-2_Sample_20201113_044829.fsa\n', 'G08_C1-123HLA_C_4R_20201119_105248.ab1\n', 'G11_C1-123HLA_C_6F_20201119_115401.ab1\n', 'GF_2ng_C04_7_B24-030_3_20210203_195503.fsa\n', 'GF_2ng_OSRON_A07_1_B8-050_1_20210325_053929.fsa\n', 'GF_2ng_OSRON_A09_3_B24-030_2_20210325_004126.fsa\n', 'GF_2ng_OSRON_B09_6_B24-030_2_20210325_004129.fsa\n', 'GF_2ng_OSRON_C07_3_B8-010_2_20210325_061440.fsa\n', 'GF_2ng_OSRON_C09_3_B8-010_2_20210325_082021.fsa\n', 'GF_2ng_OSRON_D08_4_B8-050_2_20210325_071349.fsa\n', 'GF_2ng_OSRON_E08_14_B24-030_1_20210325_000902.fsa\n', 'GF_2ng_OSRON_F07_6_B8-050_1_20210325_053934.fsa\n', 'GF_2ng_OSRON_G07_19_B24-030_1_20210325_000907.fsa\n', 'GF_3ng_OSRON_A03_3_B24-020_4_20210331_220458.fsa\n', 'GF_3ng_OSRON_A03_3_B24-030_3_20210331_231125.fsa\n', 'GF_3ng_OSRON_B02_2_B8-010_2_20210331_154100.fsa\n', 'GF_3ng_OSRON_C03_9_B24-030_2_20210331_154519.fsa\n', 'GF_3ng_OSRON_E02_14_B24-030_2_20210331_154524.fsa\n', 'GF_3ng_OSRON_E03_15_B24-020_2_20210331_143800.fsa\n', 'GF_3ng_OSRON_G01_7_B8-050_1_20210331_093226.fsa\n', 'GF_3ng_OSRON_G02_20_B24-030_2_20210331_154530.fsa\n', 'GF_3ng_OSRON_G02_7_B8-050_2_20210331_130344.fsa\n', 'GF_3ng_OSRON_G03_21_B24-030_1_20210331_150820.fsa\n', 'GF_3ng_OSRON_H01_8_B8-050_1_20210331_093227.fsa\n', 'GF_4.5ng_OSRON_A04_1_B8-010_2_20210331_205940.fsa\n', 'GF_4.5ng_OSRON_A06_3_B24-030_4_20210401_022947.fsa\n', 'GF_4.5ng_OSRON_B03_2_B8-010_2_20210331_182015.fsa\n', 'GF_4.5ng_OSRON_B04_4_B24-030_4_20210401_022948.fsa\n', 'GF_4.5ng_OSRON_C03_3_B8-010_2_20210331_182016.fsa\n', 'GF_4.5ng_OSRON_C04_7_B24-020_4_20210401_012354.fsa\n', 'GF_4.5ng_OSRON_D04_4_B8-050_2_20210331_182142.fsa\n', 'GF_4.5ng_OSRON_E04_13_B24-020_4_20210401_012400.fsa\n', 'GF_4.5ng_OSRON_E06_15_B24-030_4_20210401_022959.fsa\n', 'GF_4.5ng_OSRON_F04_6_B8-010_2_20210331_205945.fsa\n', 'GF_4.5ng_OSRON_G04_7_B8-050_2_20210331_182145.fsa\n', 'GF_4.5ng_OSRON_G05_20_B24-030_4_20210401_023004.fsa\n', 'GF_4.5ng_OSRON_H04_22_B24-030_1_20210331_174928.fsa\n', 'GF_6ng_OSRON_A07_1_B24-020_4_20210401_040524.fsa\n', 'GF_6ng_OSRON_A07_1_B24-030_1_20210331_203015.fsa\n', 'GF_6ng_OSRON_A08_2_B24-030_4_20210401_051058.fsa\n', 'GF_6ng_OSRON_E07_13_B24-020_4_20210401_040536.fsa\n', 'GF_6ng_OSRON_E07_13_B24-030_2_20210331_210735.fsa\n', 'GF_6ng_OSRON_G07_19_B24-030_4_20210401_051115.fsa\n', 'GF_AL_H05_23_B24-030_2_20210203_192246.fsa\n', 'GF_AL_H05_23_B24-030_3_20210203_195519.fsa\n', 'GF_AL_OSRON_H01_22_B24-020_1_20210324_214848.fsa\n', 'GF_AL_OSRON_H01_22_B24-030_1_20210324_215945.fsa\n', 'GF_AL_OSRON_H07_22_B24-030_2_20210325_004145.fsa\n', 'H01_C1-130HLA_B_2F_20201118_192225.ab1\n', 'H01_C1-130HLA_C_1F_20201119_084956.ab1\n', 'H02_C1-130HLA_B_2R_20201118_192226.ab1\n', 'H04_C1-130HLA_B_3R_20201118_202340.ab1\n', 'H04_TrueMark_11703(1685)T_Sample_20201112_150810.fsa\n', 'H04_TrueMark_11703(1685)T_Sample_20201113_052312.fsa\n', 'H04_TrueMark_11703(1685)T_Sample_20201113_080347.fsa\n', 'H04_TrueMark_11703(1685)T_Sample_20201113_084253.fsa\n', 'H05_C1-130HLA_C_3F_20201119_095137.ab1\n', 'H05_TrueMark_CEPH-2_Sample_20201112_182330.fsa\n', 'H06_TrueMark_CEPH-10_Sample_20201112_200805.fsa\n', 'H06_TrueMark_CEPH-10_Sample_20201113_001508.fsa\n', 'H07_C1-130HLA_C_4F_20201119_105250.ab1\n', 'H08_C1-130HLA_C_4R_20201119_105251.ab1\n', 'H11_C1-130HLA_C_6F_20201119_115404.ab1\n', 'IDP_AL_G01_19_B24-030_1_20210203_170540.fsa\n', 'IDP_AL_G01_19_B24-030_3_20210203_181738.fsa\n', 'IDP_AL_H01_22_B24-030_3_20210203_181741.fsa\n', 'IDP_AL_H01_22_B24-030_4_20210204_020051.fsa\n', 'IFP_3ng_OSRON_A01_1_B24-020_4_20210331_000526.fsa\n', 'IFP_3ng_OSRON_A03_3_B24-020_2_20210330_160104.fsa\n', 'IFP_3ng_OSRON_A03_3_B24-020_3_20210330_232812.fsa\n', 'IFP_3ng_OSRON_B02_5_B24-030_2_20210330_201043.fsa\n', 'IFP_3ng_OSRON_D01_10_B24-020_2_20210330_160111.fsa\n', 'IFP_3ng_OSRON_D01_10_B24-030_2_20210330_201048.fsa\n', 'IFP_3ng_OSRON_D02_4_B8-010_2_20210330_193338.fsa\n', 'IFP_3ng_OSRON_E03_15_B24-020_2_20210330_160116.fsa\n', 'IFP_3ng_OSRON_F02_17_B24-020_2_20210330_160118.fsa\n', 'IFP_3ng_OSRON_F02_6_B8-010_1_20210316_154421.fsa\n', 'IFP_3ng_OSRON_F03_18_B24-020_4_20210331_000543.fsa\n', 'IFP_3ng_OSRON_H01_22_B24-020_4_20210331_000547.fsa\n', 'IFP_3ng_OSRON_H01_8_B8-010_1_20210330_161630.fsa\n', 'IFP_3ng_OSRON_H02_8_B8-010_1_20210316_154423.fsa\n', 'IFP_3ng_OSRON_H02_8_B8-050_2_20210330_174229.fsa\n', 'IFP_4.5ng_OSRON_A04_1_B8-050_2_20210330_230024.fsa\n', 'IFP_4.5ng_OSRON_B04_4_B24-020_4_20210331_024655.fsa\n', 'IFP_4.5ng_OSRON_B05_5_B24-030_4_20210331_073316.fsa\n', 'IFP_4.5ng_OSRON_C03_3_B8-050_2_20210330_202120.fsa\n', 'IFP_4.5ng_OSRON_C05_8_B24-020_4_20210331_024659.fsa\n', 'IFP_4.5ng_OSRON_E04_13_B24-030_4_20210331_073324.fsa\n', 'IFP_4.5ng_OSRON_H04_8_B8-010_2_20210331_005208.fsa\n', 'IFP_6ng_OSRON_A08_2_B24-020_4_20210331_052816.fsa\n', 'IFP_6ng_OSRON_D05_4_B8-010_2_20210331_033107.fsa\n', 'IFP_6ng_OSRON_D07_10_B24-020_4_20210331_052824.fsa\n', 'IFP_6ng_OSRON_D07_10_B24-030_2_20210331_021107.fsa\n', 'IFP_6ng_OSRON_G05_7_B8-010_2_20210331_033110.fsa\n', 'IFP_6ng_OSRON_G06_7_B8-050_2_20210331_041809.fsa\n', 'IFP_6ng_OSRON_G09_21

In [17]:
lines[::2]

['A01_A01_Sample_20201223_182440.fsa\n',
 'A02_C1-106HLA_B_2R_20201118_192205.ab1\n',
 'A03_C1-106HLA_B_3F_20201118_192206.ab1\n',
 'A04_TrueMark_S06-010363_Sample_20201112_143033.fsa\n',
 'A04_TrueMark_S06-010363_Sample_20201112_225639.fsa\n',
 'A05_C1-106HLA_C_3F_20201119_095116.ab1\n',
 'A08_C1-106HLA_C_4R_20201119_105230.ab1\n',
 'B02_C1-107HLA_B_2R_20201118_192208.ab1\n',
 'B04_C1-107HLA_C_2R_20201119_095118.ab1\n',
 'B04_TrueMark_3435(1420)T_Sample_20201112_162600.fsa\n',
 'B04_TrueMark_3435(1420)T_Sample_20201113_075104.fsa\n',
 'B05_C1-107HLA_C_3F_20201119_095119.ab1\n',
 'B05_TrueMark_S06-012578_Sample_20201113_021200.fsa\n',
 'B05_TrueMark_S06-012578_Sample_20201113_101927.fsa\n',
 'B07_C1-107HLA_C_4F_20201119_105232.ab1\n',
 'B08_C1-107HLA_C_4R_20201119_105233.ab1\n',
 'BDDpUC19_BDXFstSeq50POP7_RT_B01_2_20210630_125633.ab1\n',
 'BDDpUC19_BDXFstSeq50POP7_RT_E02_14_20210625_203531.ab1\n',
 'BDDpUC19_BDXRpdSeq50POP7_RT_A01_1_20210625_185543.ab1\n',
 'BDDpUC19_BDXRpdSeq50POP7_RT_C02_8_20210625_231638.ab1\n',
 'BDDpUC19_BDXRpdSeq50POP7_RT_D03_12_20210625_223912.ab1\n',
 'BDDpUC19_BDXRpdSeq50POP7_RT_D03_12_20210625_231642.ab1\n',
 'BDDpUC19_BDXRpdSeq50POP7_RT_E02_14_20210625_231644.ab1\n',
 'BDDpUC19_BDXRpdSeq50POP7_RT_E03_15_20210625_231645.ab1\n',
 'BDDpUC19_BDXRpdSeq50POP7_RT_F01_16_20210625_231646.ab1\n',
 'BDDpUC19_BDXRpdSeq50POP7_RT_F03_18_20210625_231648.ab1\n',
 'BDDpUC19_BDXRpdSeq50POP7_RT_H02_23_20210625_231653.ab1\n',
 'BDDpUC19_BDXStdSeq50POP7_RT_E02_14_20210625_163043.ab1\n',
 'BDDpUC19_RpdSeq50POP7_15C20RH_D02_11_20210625_165855.ab1\n',
 'BDDpUC19_RpdSeq50POP7_RT_C03_9_20210628_113355.ab1\n',
 'BDDpUC19_RpdSeq50POP7_RT_E02_14_20210628_113400.ab1\n',
 'BDDpUC19_RpdSeq50POP7_RT_E03_15_20210628_113401.ab1\n',
 'BDDpUC19_RpdSeq50POP7_RT_F03_18_20210628_113404.ab1\n',
 'BDDpUC19_RpdSeq50POP7_RT_G03_21_20210628_113407.ab1\n',
 'BDT1.1_BDXFstSeq50POP7_RT_A03_3_20210628_162552.ab1\n',
 'BDT1.1_BDXRpd36POP7_RT_C09_9_20210625_140407.ab1\n',
 'BDT1.1_BDXRpdSeq50POP6_RT_G01_19_20210630_152503.ab1\n',
 'BDT1.1_FST50POP7_15C20RH_C01_7_20210621_161130.ab1\n',
 'BDT1.1_FstSeq36POP7_RT_C04_7_20210623_201732.ab1\n',
 'BDT1.1_FstSeq50POP6_15C20RH_D05_11_20210622_000921.ab1\n',
 'BDT1.1_FstSeq50POP6_RT_E01_5_20210617_165257.ab1\n',
 'BDT1.1_FstSeq50POP7_30C80RH_C01_3_20210725_154808.ab1\n',
 'BDT1.1_MSeqID50POP6_15C20RH_C04_7_20210618_172630.ab1\n',
 'BDT1.1_MSeqID50POP6_15C20RH_H05_23_20210618_151658.ab1\n',
 'BDT1.1_MSeqID50POP6_30C80RH_G03_21_20210725_130051.ab1\n',
 'BDT1.1_MSeqID50POP6_RT_D01_4_20210621_215036.ab1\n',
 'BDT1.1_RpdSeq36P0P7_RT_D03_12_20210630_161002.ab1\n',
 'BDT1.1_RpdSeq36POP4_15C20RH_H01_22_20210624_122344.ab1\n',
 'BDT1.1_RpdSeq36POP4_30C80RH_C04_7_20210803_161126.ab1\n',
 'BDT1.1_RpdSeq36POP6_30C80RH_B05_5_20210802_133735.ab1\n',
 'BDT1.1_RpdSeq36POP7_RT_A05_2_20210624_124813.ab1\n',
 'BDT1.1_RpdSeq50POP6_RT_D01_4_20210621_152032.ab1\n',
 'BDT1.1_StdSeq50POP6_15C20RH_G06_21_20210617_212503.ab1\n',
 'BDT1.1_StdSeq50POP7_30C80RH_A01_1_20210724_114753.ab1\n',
 'BDT3.1_BDXFstSeq50POP7_RT_C04_7_20210628_172750.ab1\n',
 'BDT3.1_BDXRpdSeq50POP7_RT_A02_1_20210629_154455.ab1\n',
 'BDT3.1_BDXSRSeq50POP7_RT_B02_2_20210706_133644.ab1\n',
 'BDT3.1_BDXSRSeq50POP7_RT_D06_12_20210624_151913.ab1\n',
 'BDT3.1_BDXSRSeq50POP7_RT_G04_19_20210624_151920.ab1\n',
 'BDT3.1_FstSeq36POP7_15C20RH_E06_15_20210623_153418.ab1\n',
 'BDT3.1_FstSeq36POP7_RT_D08_11_20210623_211437.ab1\n',
 'BDT3.1_FstSeq36POP7_RT_F01_16_20210713_110912.ab1\n',
 'BDT3.1_FstSeq50POP6_15C20RH_F09_18_20210622_013452.ab1\n',
 'BDT3.1_FstSeq50POP7_30C80RH_C04_7_20210725_150410.ab1\n',
 'BDT3.1_FstSeq50POP7_30C80RH_E02_5_20210725_175139.ab1\n',
 'BDT3.1_FstSeq50POP7_30C80RH_H06_24_20210725_160542.ab1\n',
 'BDT3.1_FstSeq50POP7_RT_D04_10_20210622_192739.ab1\n',
 'BDT3.1_FstSeq50POP7_RT_G05_20_20210622_182700.ab1\n',
 'BDT3.1_RpdSeq36POP6_RT_D05_11_20210622_135851.ab1\n',
 'BDT3.1_RpdSeq36POP6_RT_G04_19_20210617_192105.ab1\n',
 'BDT3.1_RpdSeq50POP6_15C20RH_C08_8_20210621_185011.ab1\n',
 'BDT3.1_RpdSeq50POP6_15C20RH_H09_24_20210621_185027.ab1\n',
 'BDT3.1_RpdSeq50POP6_RT_F04_16_20210621_201558.ab1\n',
 'BDT3.1_StdSeq50POP7_15C20RH_E04_13_20210617_162019.ab1\n',
 'BVMM1000_FA50POP7_15C20RH_B03_6_20210616_142426.fsa\n',
 'BVMM1000_FA50POP7_15C20RH_E04_13_20210616_161449.fsa\n',
 'BVMM1000_FA50POP7_30C80RH_B05_5_20210720_195131.fsa\n',
 'BVMM1000_FA50POP7_30C80RH_D04_10_20210720_161225.fsa\n',
 'BVMM1000_FA50POP7_30C80RH_H02_8_20210720_161243.fsa\n',
 'BVMM1000_FA50POP7_RT_D01_10_20210616_130725.fsa\n',
 'BVMM1000_FA50POP7_RT_D05_11_20210616_161401.fsa\n',
 'BVMM1000_FA50POP7_RT_F02_17_20210616_121431.fsa\n',
 'BVMM1250_LFA50POP7_15C20RH_A06_3_20210610_153313.fsa\n',
 'BVMM1250_LFA50POP7_15C20RH_D01_4_20210611_092147.fsa\n',
 'BVMM1250_LFA50POP7_15C20RH_E01_5_20210610_112839.fsa\n',
 'BVMM1250_LFA50POP7_15C20RH_G02_20_20210610_173540.fsa\n',
 'BVMM1250_LFA50POP7_30C80RH_B01_2_20210721_114400.fsa\n',
 'BVMM1250_LFA50POP7_30C80RH_B02_5_20210721_114437.fsa\n',
 'BVMM1250_LFA50POP7_30C80RH_C02_8_20210721_114440.fsa\n',
 'BVMM1250_LFA50POP7_30C80RH_G01_19_20210718_165513.fsa\n',
 'BVMM1250_LFA50POP7_30C80RH_H01_22_20210721_114454.fsa\n',
 'BVMM1250_LFA50POP7_RT_B06_6_20210610_212128.fsa\n',
 'BVMM1250_LFA50POP7_RT_E09_15_20210611_014125.fsa\n',
 'BVMM1250_LFA50POP7_RT_H04_22_20210610_212144.fsa\n',
 'C01_C1-108HLA_C_1F_20201119_084941.ab1\n',
 'C02_C1-108HLA_C_1R_20201119_084942.ab1\n',
 'C03_C1-108HLA_C_2F_20201119_084943.ab1\n',
 'C05_TrueMark_S07-025066_Sample_20201113_060622.fsa\n',
 'C06_C1-108HLA_C_3R_20201119_095123.ab1\n',
 'C08_C1-108HLA_C_4R_20201119_105236.ab1\n',
 'D04_TrueMark_S08-021103_Sample_20201112_170512.fsa\n',
 'D05_TrueMark_Control-1_Sample_20201112_235004.fsa\n',
 'D05_TrueMark_Control-1_Sample_20201113_025110.fsa\n',
 'D07_C1-115HLA_C_4F_20201119_105238.ab1\n',
 'DS33IS_FA36POP4_15C20RH_A02_2_20210628_123003.fsa\n',
 'DS33IS_FA36POP4_20210615_E05_14_20210615_112827.fsa\n',
 'DS33IS_FA36POP4_20210615_G06_21_20210615_161858.fsa\n',
 'DS33IS_FA36POP4_30C80RH_A01_1_20210720_001301.fsa\n',
 'DS33IS_FA36POP4_30C80RH_B03_6_20210720_001306.fsa\n',
 'DS33IS_FA36POP4_30C80RH_D02_4_20210719_220229.fsa\n',
 'DS33IS_FA36POP4_30C80RH_E01_13_20210719_224629.fsa\n',
 'DS33IS_FA36POP4_30C80RH_E03_15_20210720_001315.fsa\n',
 'DS33IS_FA36POP4_30C80RH_G05_20_20210720_011830.fsa\n',
 'DS33IS_FA36POP4_RT_A04_1_20210615_113517.fsa\n',
 'DS33IS_FA36POP4_RT_B06_6_20210809_140951.fsa\n',
 'DS33IS_FA36POP4_RT_C03_9_20210615_151140.fsa\n',
 'DS33IS_FA36POP4_RT_D06_12_20210615_113528.fsa\n',
 'DS33IS_FA36POP4_RT_F02_17_20210615_140909.fsa\n',
 'DS33IS_FA36POP4_RT_F04_16_20210615_113532.fsa\n',
 'DS33IS_FA36POP4_RT_H04_22_20210614_124706.fsa\n',
 'DS33IS_FA36POP6_30C80RH_B02_2_20210803_131726.fsa\n',
 'DS33IS_FA36POP6_30C80RH_F01_16_20210719_143647.fsa\n',
 'DS33IS_FA36POP7_15C20RH_D04_10_20210609_121741.fsa\n',
 'DS33IS_FA36POP7_RT_C01_7_20210609_100426.fsa\n',
 'E01_C1-116HLA_C_1F_20201119_084947.ab1\n',
 'E02_E02_Sample_20201223_182453.fsa\n',
 'E03_C1-116HLA_C_2F_20201119_084949.ab1\n',
 'E04_C1-116HLA_C_2R_20201119_095127.ab1\n',
 'E06_C1-116HLA_C_3R_20201119_095129.ab1\n',
 'F01_C1-122HLA_A_1F_20201118_151730.ab1\n',
 'F04_TrueMark_S07-001490_Sample_20201112_194132.fsa\n',
 'F04_TrueMark_S07-001490_Sample_20201113_040921.fsa\n',
 'G03_C1-123HLA_B_3F_20201118_192224.ab1\n',
 'G04_C1-123HLA_B_3R_20201118_202337.ab1\n',
 'G04_TrueMark_S08-021103_Sample_20201113_033204.fsa\n',
 'G04_TrueMark_S08-021103_Sample_20201113_072440.fsa\n',
 'G05_TrueMark_CEPH-10_Sample_20201112_205944.fsa\n',
 'G06_TrueMark_CEPH-2_Sample_20201113_044829.fsa\n',
 'G11_C1-123HLA_C_6F_20201119_115401.ab1\n',
 'GF_2ng_OSRON_A07_1_B8-050_1_20210325_053929.fsa\n',
 'GF_2ng_OSRON_B09_6_B24-030_2_20210325_004129.fsa\n',
 'GF_2ng_OSRON_C09_3_B8-010_2_20210325_082021.fsa\n',
 'GF_2ng_OSRON_E08_14_B24-030_1_20210325_000902.fsa\n',
 'GF_2ng_OSRON_G07_19_B24-030_1_20210325_000907.fsa\n',
 'GF_3ng_OSRON_A03_3_B24-030_3_20210331_231125.fsa\n',
 'GF_3ng_OSRON_C03_9_B24-030_2_20210331_154519.fsa\n',
 'GF_3ng_OSRON_E03_15_B24-020_2_20210331_143800.fsa\n',
 'GF_3ng_OSRON_G02_20_B24-030_2_20210331_154530.fsa\n',
 'GF_3ng_OSRON_G03_21_B24-030_1_20210331_150820.fsa\n',
 'GF_4.5ng_OSRON_A04_1_B8-010_2_20210331_205940.fsa\n',
 'GF_4.5ng_OSRON_B03_2_B8-010_2_20210331_182015.fsa\n',
 'GF_4.5ng_OSRON_C03_3_B8-010_2_20210331_182016.fsa\n',
 'GF_4.5ng_OSRON_D04_4_B8-050_2_20210331_182142.fsa\n',
 'GF_4.5ng_OSRON_E06_15_B24-030_4_20210401_022959.fsa\n',
 'GF_4.5ng_OSRON_G04_7_B8-050_2_20210331_182145.fsa\n',
 'GF_4.5ng_OSRON_H04_22_B24-030_1_20210331_174928.fsa\n',
 'GF_6ng_OSRON_A07_1_B24-030_1_20210331_203015.fsa\n',
 'GF_6ng_OSRON_E07_13_B24-020_4_20210401_040536.fsa\n',
 'GF_6ng_OSRON_G07_19_B24-030_4_20210401_051115.fsa\n',
 'GF_AL_H05_23_B24-030_3_20210203_195519.fsa\n',
 'GF_AL_OSRON_H01_22_B24-030_1_20210324_215945.fsa\n',
 'H01_C1-130HLA_B_2F_20201118_192225.ab1\n',
 'H02_C1-130HLA_B_2R_20201118_192226.ab1\n',
 'H04_TrueMark_11703(1685)T_Sample_20201112_150810.fsa\n',
 'H04_TrueMark_11703(1685)T_Sample_20201113_080347.fsa\n',
 'H05_C1-130HLA_C_3F_20201119_095137.ab1\n',
 'H06_TrueMark_CEPH-10_Sample_20201112_200805.fsa\n',
 'H07_C1-130HLA_C_4F_20201119_105250.ab1\n',
 'H11_C1-130HLA_C_6F_20201119_115404.ab1\n',
 'IDP_AL_G01_19_B24-030_3_20210203_181738.fsa\n',
 'IDP_AL_H01_22_B24-030_4_20210204_020051.fsa\n',
 'IFP_3ng_OSRON_A03_3_B24-020_2_20210330_160104.fsa\n',
 'IFP_3ng_OSRON_B02_5_B24-030_2_20210330_201043.fsa\n',
 'IFP_3ng_OSRON_D01_10_B24-030_2_20210330_201048.fsa\n',
 'IFP_3ng_OSRON_E03_15_B24-020_2_20210330_160116.fsa\n',
 'IFP_3ng_OSRON_F02_6_B8-010_1_20210316_154421.fsa\n',
 'IFP_3ng_OSRON_H01_22_B24-020_4_20210331_000547.fsa\n',
 'IFP_3ng_OSRON_H02_8_B8-010_1_20210316_154423.fsa\n',
 'IFP_4.5ng_OSRON_A04_1_B8-050_2_20210330_230024.fsa\n',
 'IFP_4.5ng_OSRON_B05_5_B24-030_4_20210331_073316.fsa\n',
 'IFP_4.5ng_OSRON_C05_8_B24-020_4_20210331_024659.fsa\n',
 'IFP_4.5ng_OSRON_H04_8_B8-010_2_20210331_005208.fsa\n',
 'IFP_6ng_OSRON_D05_4_B8-010_2_20210331_033107.fsa\n',
 'IFP_6ng_OSRON_D07_10_B24-030_2_20210331_021107.fsa\n',
 'IFP_6ng_OSRON_G06_7_B8-050_2_20210331_041809.fsa\n',
 'IFP_6ng_OSRON_H07_22_B24-020_1_20210330_204708.fsa\n',
 'NGMD_1.5ng_OSRON_A01_1_B24-020_1_20210401_104236.fsa\n',
 'NGMD_1.5ng_OSRON_A01_1_B8-010_2_20210401_112205.fsa\n',
 'NGMD_1.5ng_OSRON_B03_6_B24-020_2_20210401_111959.fsa\n',
 'NGMD_1.5ng_OSRON_C01_3_B8-010_2_20210401_112207.fsa\n',
 'NGMD_1.5ng_OSRON_C03_9_B24-020_2_20210401_112002.fsa\n',
 'NGMD_1.5ng_OSRON_E03_15_B24-020_2_20210401_112008.fsa\n',
 'NGMD_1.5ng_OSRON_F01_6_B8-050_1_20210401_104411.fsa\n',
 'NGMD_1.5ng_OSRON_F03_18_B24-030_2_20210401_112515.fsa\n',
 'NGMD_1.5ng_OSRON_H01_22_B24-020_1_20210318_144700.fsa\n',
 'NGMD_1.5ng_OSRON_H02_23_B24-020_2_20210401_112016.fsa\n',
 'NGMD_2.25ng_OSRON_A04_1_B8-010_2_20210401_191956.fsa\n',
 'NGMD_2.25ng_OSRON_B03_2_B8-010_2_20210401_164040.fsa\n',
 'NGMD_2.25ng_OSRON_D04_4_B8-050_2_20210401_193352.fsa\n',
 'NGMD_2.25ng_OSRON_G06_21_B24-020_2_20210401_140143.fsa\n',
 'NGMD_2.25ng_OSRON_H05_23_B24-020_2_20210401_140145.fsa\n',
 'NGMD_2.25ng_OSRON_H06_24_B24-020_2_20210401_140146.fsa\n',
 'NGMD_3ng_OSRON_A07_1_B24-030_2_20210401_164719.fsa\n',
 'NGMD_3ng_OSRON_B08_5_B24-020_4_20210402_004724.fsa\n',
 'NGMD_3ng_OSRON_E09_15_B24-030_3_20210402_005121.fsa\n',
 'NGMD_3ng_OSRON_G06_7_B8-050_2_20210402_005139.fsa\n',
 'NGMD_3ng_OSRON_H07_22_B24-030_2_20210401_164740.fsa\n',
 'NGMD_AL_OSRON_H04_22_B24-020_1_20210325_222248.fsa\n',
 'NGMD_AL_OSRON_H04_8_B8-010_1_20210326_013529.fsa\n',
 'SNP_SNP50POP7_15C20RH_A02_1_20210616_181620.fsa\n',
 'SNP_SNP50POP7_15C20RH_B02_5_20210616_171738.fsa\n',
 'SNP_SNP50POP7_15C20RH_C06_9_20210616_190659.fsa\n',
 'SNP_SNP50POP7_15C20RH_E02_14_20210616_171747.fsa\n',
 'SNP_SNP50POP7_15C20RH_E03_15_20210616_174601.fsa\n',
 'SNP_SNP50POP7_15C20RH_F04_16_20210616_181513.fsa\n',
 'SNP_SNP50POP7_20210616_E06_15_20210616_182609.fsa\n',
 'SNP_SNP50POP7_20210616_G03_21_20210616_165845.fsa\n',
 'SNP_SNP50POP7_30C20RH_B02_2_20210720_135504.fsa\n',
 'SNP_SNP50POP7_30C80RH_C01_7_20210720_122101.fsa\n',
 'SNP_SNP50POP7_30C80RH_C05_8_20210720_134749.fsa\n',
 'SNP_SNP50POP7_30C80RH_E02_14_20210720_122108.fsa\n',
 'SNP_SNP50POP7_30C80RH_F03_18_20210720_124930.fsa\n',
 'SNP_SNP50POP7_30C80RH_H05_23_20210720_131850.fsa\n',
 'SNP_SNP50POP7_RT_B04_4_20210616_191510.fsa\n',
 'SNP_SNP50POP7_RT_D06_12_20210616_191518.fsa\n',
 'SNP_SNP50POP7_RT_G01_19_20210611_162559.fsa\n',
 'SNP_SNP50POP7_RT_G03_21_20210611_165407.fsa\n',
 'SNP_SNP50POP7_RT_H01_8_20210616_165740.fsa\n',
 'SNP_SNP50POP7_RT_H03_24_20210611_162604.fsa\n']

In [82]:
import pandas as pd
country=pd.read_csv("/Users/aswathy.n/Aswathy/My_learning/programming_learning/GL_AIML/KeyAreas/UdemyTrials/GenAIWithChatGPTNOpenAIAPI_Udemy/downloads4/countries.csv")
print(country.head())
print(country.shape)
print(country.describe())

FileNotFoundError: [Errno 2] No such file or directory: '/Users/aswathy.n/Aswathy/My_learning/programming_learning/GL_AIML/KeyAreas/UdemyTrials/GenAIWithChatGPTNOpenAIAPI_Udemy/downloads4/countries.csv'

In [46]:
country.columns

Index(['Country', 'Capital City', 'Area (km²)', 'Population'], dtype='object')

In [32]:
country.dtypes

Country         object
Capital City    object
Area (km²)      object
Population      object
dtype: object

In [27]:
country['Area (km²)']

0      9,388,211
1      3,287,263
2      9,525,067
3      1,904,569
4        881,913
5      8,515,767
6        923,768
7        148,460
8     17,098,242
9      1,964,375
10       377,975
11     1,104,300
12       300,000
13     1,001,450
14       331,212
15     2,344,858
16       783,562
17     1,648,195
18       357,022
19       551,695
20       243,610
21       513,120
22     1,221,037
23       945,087
24       301,340
25       676,578
26       100,210
27     1,141,748
28       505,992
29       603,500
Name: Area (km²), dtype: object

In [ ]:
#country['Area (km²)']=country['Area (km²)'].str.replace(",","").astype(np.int64)
#country['Area (km²)']= pd.to_numeric(country['Area (km²)'], errors='coerce').fillna(0).astype(np.int64)
#country['Area (km²)']=country['Area (km²)'].str.replace(",","").astype(np.int64)
country['Area (km²)']=country['Area (km²)'].str.replace(",","").astype(np.int64)
country['Area (km²)']=pd.to_numeric(country['Area (km²)'], errors='coerce').fillna(0).astype(np.int64)
country['Area (km²)']=pd.to_numeric(country['Area (km²)'], errors='coerce').fillna(0).astype(np.int64)
country.dtypes

Country         object
Capital City    object
Area (km²)       int64
Population      object
dtype: object

In [34]:
country['Area (km²)']

0      9388211
1      3287263
2      9525067
3      1904569
4       881913
5      8515767
6       923768
7       148460
8     17098242
9      1964375
10      377975
11     1104300
12      300000
13     1001450
14      331212
15     2344858
16      783562
17     1648195
18      357022
19      551695
20      243610
21      513120
22     1221037
23      945087
24      301340
25      676578
26      100210
27     1141748
28      505992
29      603500
Name: Area (km²), dtype: int64

In [35]:
#convert string (actually number) series to an integer series
country['Population']=country['Population'].str.replace(",","").astype(np.int64)
#country['Population']= pd.to_numeric(country['Population'], errors='coerce').fillna(0).astype(np.int64)
country.dtypes, country.select_dtypes(include='int64')

(Country         object
 Capital City    object
 Area (km²)       int64
 Population       int64
 dtype: object,
     Area (km²)  Population
 0      9388211  1439323776
 1      3287263  1380004385
 2      9525067   331002651
 3      1904569   273523615
 4       881913   220892340
 5      8515767   212559417
 6       923768   206139589
 7       148460   164689383
 8     17098242   145934462
 9      1964375   128932753
 10      377975   126476461
 11     1104300   114963588
 12      300000   109581078
 13     1001450   102334404
 14      331212    97338579
 15     2344858    89561403
 16      783562    84339067
 17     1648195    83992949
 18      357022    83783942
 19      551695    65273511
 20      243610    67886011
 21      513120    69799978
 22     1221037    59308690
 23      945087    59734218
 24      301340    60461826
 25      676578    54409800
 26      100210    51269185
 27     1141748    50882891
 28      505992    46754778
 29      603500    43733762)

In [116]:
country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       30 non-null     object
 1   Capital City  30 non-null     object
 2   Area (km²)    30 non-null     int64
 3   Population    30 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.1+ KB

In [117]:
np.mean(country['Population']), np.mean(country['Area (km²)'])

(200829616.4, 2289670.8666666667)

In [118]:
country['Population'].max()

1439323776

In [119]:
country.describe()

         Area (km²)    Population
count  3.000000e+01  3.000000e+01
mean   2.289671e+06  2.008296e+08
std    3.821067e+06  3.362632e+08
min    1.002100e+05  4.373376e+07
25%    4.099792e+05  6.166475e+07
50%    9.028405e+05  9.344999e+07
75%    1.840476e+06  1.600007e+08
max    1.709824e+07  1.439324e+09

In [36]:
country[country['Country']=='India']['Capital City']

1    New Delhi
Name: Capital City, dtype: object

In [28]:
country.index[country['Country']=='India'].tolist(), list(country.index[country['Country']=='India']), country[country['Country']=='India'].index

([1], [1], Int64Index([1], dtype='int64'))

In [49]:
country.loc[country['Country']=='India','Capital City']

1    New Delhi
Name: Capital City, dtype: object

In [129]:
country[country['Population']==country['Population'].max()][['Country','Capital City']]

  Country Capital City
0   China      Beijing

In [279]:
with open ("/Users/aswathy.n/Aswathy/My_learning/programming_learning/GL_AIML/KeyAreas/UdemyTrials/GenAIWithChatGPTNOpenAIAPI_Udemy/downloads4/countries_writeTrial.csv","w") as Fw:
        Fw.write("Write trial\n")
        Fw.write(str(country[country['Country']=='India']['Capital City']))

In [280]:
#With open file in append mode
with open ("/Users/aswathy.n/Aswathy/My_learning/programming_learning/GL_AIML/KeyAreas/UdemyTrials/GenAIWithChatGPTNOpenAIAPI_Udemy/downloads4/countries_writeTrial.csv","a") as Fw:
        Fw.write("Write trial\n")
        Fw.write(str(country[country['Country']=='India']['Capital City']))

In [135]:
np.product([1,3,4,5])

60

In [56]:
my_l=[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
my_l[6:len(my_l)], my_l[len(my_l):5:-1], my_l[len(my_l)-2:3:-2]

([3, 2, 1, 0], [0, 1, 2, 3], [1, 3, 5])

In [142]:
List = [23, 65, 19, 90]

List[len(List)-1], List[0]= List[0], List[len(List)-1]

List

[90, 65, 19, 23]

In [1]:
a = [1,2,3,7,2,1,5,6,4,8,5,4]
#uniq list 
"""
b=set(a)
print(b)
"""
dup = set(a)
uniq = []
for x in a:
    if x not in uniq:
        uniq.append(x)
       # dup.add(x)
print(dup)
print(uniq)

{1, 2, 3, 4, 5, 6, 7, 8}
[1, 2, 3, 7, 5, 6, 4, 8]

In [3]:
uniq1=uniq.copy()
uniq1

[1, 2, 3, 7, 5, 6, 4, 8]

In [4]:
import copy
uniq2=copy.copy(uniq1)
uniq2

[1, 2, 3, 7, 5, 6, 4, 8]

In [5]:
uniq1.append([16])
uniq1.extend([24])
uniq1.append(12)
uniq1, uniq2

([1, 2, 3, 7, 5, 6, 4, 8, [16], 24, 12], [1, 2, 3, 7, 5, 6, 4, 8])

In [157]:
uniq3=copy.deepcopy(uniq2)
uniq2.append(123)
uniq2, uniq3

([1, 2, 3, 7, 5, 6, 4, 8, 123], [1, 2, 3, 7, 5, 6, 4, 8])

In [3]:
#List comprehension common elements
l1=[1,4,3,6]
l2=[3,2,8,1]
[x for x in l1 for y in l2 if x==y], [x for (i,x) in enumerate(l1) for (j,y) in enumerate(l2) if ((x==y) &(i==j))]

([1, 3], [])

In [103]:
List=["Cat", "Dog", "Elephant", "Fox", "Tiger", "Lion", "Ponda"]

List1=[x for (i,x) in enumerate (List) if i not in [0,4,5]]
List1, [x for x in List if len(x)>=4], [x[0] for x in List if len(x)>=4]

(['Dog', 'Elephant', 'Fox', 'Ponda'],
 ['Elephant', 'Tiger', 'Lion', 'Ponda'],
 ['E', 'T', 'L', 'P'])

In [57]:
#list comprehension even numbers
L=[7,32,81,20,25,14,23,27]

Leven=[x for x in L if x%2 ==0]
Leven

[32, 20, 14]

In [3]:
from random import shuffle


animal = ["Cat", "Dog", "Elephant", "Fox", "Tiger", "Lion", "Ponda"]
shuffle(animal)
print(animal)

['Fox', 'Cat', 'Tiger', 'Elephant', 'Lion', 'Dog', 'Ponda']

In [178]:
t = [[20,30,70],[30,90,10], [30,20], [70,90,10,80]]
flat_list = [item for sublist in t for item in sublist]

In [179]:
flat_list

[20, 30, 70, 30, 90, 10, 30, 20, 70, 90, 10, 80]

In [7]:
import numpy as np
Number = [10, 20, 30, 40]
animal = ["Cat", "Dog", "Lion", "Ponda"]
new_l=Number+animal; newNL=Number+[25]; newNLN=np.array(Number)+25
new_l, newNL, newNLN

([10, 20, 30, 40, 'Cat', 'Dog', 'Lion', 'Ponda'],
 [10, 20, 30, 40, 25],
 array([35, 45, 55, 65]))

In [184]:
import random
animal=["Cat", "Dog", "Elephant", "Fox", "Tiger", "Lion", "Ponda"]
print(random.choice(animal))

Ponda

In [90]:
l=[1,3,2,5,10,12]
a=l.pop(4)
b=l.pop(1)
c=l.remove(5) #remove will not return a vaue. Remove just removes an element not based on index though
l, a,b,c

([1, 2, 12], 10, 3, None)

In [106]:
#Count of all elements in a list
from collections import Counter
l = [1, 1, 2, 2, 3, 3, 4, 4, 5, 5,2, 3]
 
# driver program

d = Counter(l)
dic= dict(d)
dic, list(dic.keys()) + list(dic.values())
print([(x,y) for x,y in dict(Counter(l)).items() if y>2])
[(x,v) for x,v in dict(Counter(l)).items() if v >2],set( [l.count(x) for x in l if l.count(x)>2]), set([(x, l.count(x)) for x in l])

[(2, 3), (3, 3)]

([(2, 3), (3, 3)], {3}, {(1, 2), (2, 3), (3, 3), (4, 2), (5, 2)})

In [196]:

dic={1: [2,3], 2: [2], 3: [2], 4: [2,5], 5: 2}
dic_l=[]
for k,v in dic.items():
   dic_l.append(k)
   dic_l.append(v)
    
dic_l

[1, [2, 3], 2, [2], 3, [2], 4, [2, 5], 5, 2]

In [108]:
l1=[2,3,4,1,8,2,4] #length of unique elements in a list
res=len([x for x in l1 if l1.count(x)==1])
res, [l1.count(x) for x in l1 if l1.count(x)==1]
[(x,y) for x,y in dict(Counter(l1)).items() if y==1], sum([(y) for y in dict(Counter(l1)).values() if y==1])

([(3, 1), (1, 1), (8, 1)], 3)

In [207]:
l1=[2,3,4,1,8,2,4, 2,3,9,4,2] #Write a Python Program to Extract elements with Frequency greater than K
res=set([x for x in l1 if l1.count(x)>2])
res

{2, 4}

In [94]:
list1=[0,-1,1,-3,3,5,2,-4]
#come up with combinations of numbers from a list whose sum add up to 0
import itertools
comb=list(itertools.combinations(list1,3))
combsumTriplets0=[]
for i in comb:
    if sum(i)==0:
        print (i)
        combsumTriplets0.append(i)
    
combsumTriplets0

[x for x in comb if sum(x)==0]

(0, -1, 1)
(0, -3, 3)
(-1, 5, -4)
(1, -3, 2)
(1, 3, -4)

[(0, -1, 1), (0, -3, 3), (-1, 5, -4), (1, -3, 2), (1, 3, -4)]

In [78]:
list1=[0,-1,1,-3,3,5,2,-4]
#come up with combinations of numbers from a list whose sum add up to 0
import itertools
comb=itertools.combinations(list1,3)

sumcomb=[]
for i in comb:
    if sum(i)==0:
        sumcomb.append(i)
        
sumcomb

[(0, -1, 1), (0, -3, 3), (-1, 5, -4), (1, -3, 2), (1, 3, -4)]

In [9]:
import numpy as np
a=[4,5,6,7,8,9]
start, end=a[0], a[len(a)-1]
start, end
a1=list(np.arange(start,end+1))
#for i in range(start, end+1,1):
#    a1.append(i)
    
print(a1)
if (a==a1):
    print("the original list is in a range")
else:
    print("the original list is not in a range")

[4, 5, 6, 7, 8, 9]
the original list is in a range

In [9]:

#remove all occurances of a digit from a list
l1=[2,3,4,1,8,2,4, 2,3,9,4,2] 
x='4'

l1_str=list(map(str,l1))
l1_str=list(map(str,l1))
print(l1_str)
l1_str1=" ".join(l1_str)
l1_str1=l1_str1.replace('4',"")
print(l1_str1)
l1_str_1=l1_str1.split()
l1_str_1=list(map(int,l1_str_1))
l1_str,l1_str1,l1_str_1

['2', '3', '4', '1', '8', '2', '4', '2', '3', '9', '4', '2']
2 3  1 8 2  2 3 9  2

(['2', '3', '4', '1', '8', '2', '4', '2', '3', '9', '4', '2'],
 '2 3  1 8 2  2 3 9  2',
 [2, 3, 1, 8, 2, 2, 3, 9, 2])

In [12]:
l1=[2,3,4,1,8,2,4, 2,3,9,4,2] 
[x if x!=4 else "" for x in l1 ], [x for x in l1 if x!=4  ]

([2, 3, '', 1, 8, 2, '', 2, 3, 9, '', 2], [2, 3, 1, 8, 2, 2, 3, 9, 2])

In [109]:
[str(x).replace("4","four") if x==4 else x for x in l]

[1, 1, 2, 2, 3, 3, 'four', 'four', 5, 5, 2, 3]

In [29]:
a=[('a',1),("b",2),("c",3)]
[x[0] for x in a]

['a', 'b', 'c']

In [8]:
dic={1: 3, 2: 2, 3: 4, 4: 2, 5: 2}

rep=[]
for k,v in dic.items():
    if v>2:
      rep.append(k)  
    
rep


dic={1: [3,4], 2: [2,3], 3: [4], 4: [2], 5: [2,6]}

rep=[]
for k,v in dic.items():
    print (k,type(v))
    if len(v)>1:
      rep.append(k)  
    
rep, [x for x in dic.keys() if len(dic[x]) >1]

1 <class 'list'>
2 <class 'list'>
3 <class 'list'>
4 <class 'list'>
5 <class 'list'>

([1, 2, 5], [1, 2, 5])

In [255]:
#print list in reverse order
Olist = ['Tutor', 'joes', 'Computer', 'Education']
Olist1=Olist[-1:0:-1]
Olist1.append(Olist[0])
Olist1

['Education', 'Computer', 'joes', 'Tutor']

In [91]:
#Get the index of a word (from the list generated from a string) that starts at a given char location of a string
sen=['Tutor', 'joes', 'Computer', 'Science', 'Education', 'now']
sen_s=" ".join(sen)
k=28
sp=sen_s.find(" ",k)
print(sp)
if sp != -1:
    word=sen_s[k:sp]
elif sp== -1:
    word=sen_s[k:]
ind=sen.index(word)
ind, sen_s

37

(4, 'Tutor joes Computer Science Education now')

In [9]:
import numpy as np
l=[2,3,2,8,1,3]
l.count(2)
print(l,l.count(2) )
l.remove(2)
print(l)

[2, 3, 2, 8, 1, 3] 2
[3, 2, 8, 1, 3]

In [110]:
A="1"
B="B"

try:
    a=A/B
except Exception as e:
    if B==0:
        print ("Disision by 0!")
    elif not (type(A) is int and type(B) is int):# or isinstance(B, int)):
            print ("Both have to be numbers")
        
else:
    #a=A/B
    print ("a is ", a)
finally:
    print ("Leared try: the action except Exception as e and the failure conditions else proceed with the operation finally conclude the activities!")

Both have to be numbers
Leared try: the action except Exception as e and the failure conditions else proceed with the operation finally conclude the activities!

In [100]:
A="1"
B="B"

try:
    a=A/B
except Exception as e:
    if B==0:
        print ("Disision by 0!")
    if not ((isinstance(B, int) or (isinstance(B, int)))):
        print("inside")
        print ("Both have to be numbers")
        
else:
    #a=A/B
    print ("a is ", a)
finally:
    print ("Learning try except else finally!")

inside
Both have to be numbers
Learning try except else finally!

In [10]:
bases_num = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
index = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

powers=[x**y for i,x in enumerate (bases_num) for j,y in enumerate (index) if i==j ]
powers1=[x**y for x in bases_num for y in index]
powers, powers1

([10,
  400,
  27000,
  2560000,
  312500000,
  46656000000,
  8235430000000,
  1677721600000000,
  387420489000000000,
  100000000000000000000],
 [10,
  100,
  1000,
  10000,
  100000,
  1000000,
  10000000,
  100000000,
  1000000000,
  10000000000,
  20,
  400,
  8000,
  160000,
  3200000,
  64000000,
  1280000000,
  25600000000,
  512000000000,
  10240000000000,
  30,
  900,
  27000,
  810000,
  24300000,
  729000000,
  21870000000,
  656100000000,
  19683000000000,
  590490000000000,
  40,
  1600,
  64000,
  2560000,
  102400000,
  4096000000,
  163840000000,
  6553600000000,
  262144000000000,
  10485760000000000,
  50,
  2500,
  125000,
  6250000,
  312500000,
  15625000000,
  781250000000,
  39062500000000,
  1953125000000000,
  97656250000000000,
  60,
  3600,
  216000,
  12960000,
  777600000,
  46656000000,
  2799360000000,
  167961600000000,
  10077696000000000,
  604661760000000000,
  70,
  4900,
  343000,
  24010000,
  1680700000,
  117649000000,
  8235430000000,
  576480100000000,
  40353607000000000,
  2824752490000000000,
  80,
  6400,
  512000,
  40960000,
  3276800000,
  262144000000,
  20971520000000,
  1677721600000000,
  134217728000000000,
  10737418240000000000,
  90,
  8100,
  729000,
  65610000,
  5904900000,
  531441000000,
  47829690000000,
  4304672100000000,
  387420489000000000,
  34867844010000000000,
  100,
  10000,
  1000000,
  100000000,
  10000000000,
  1000000000000,
  100000000000000,
  10000000000000000,
  1000000000000000000,
  100000000000000000000])

In [17]:
list1 = [i if i % 2 == 0 else "odd" for i in range(1, 11)] #if else list comprehension
list1

['odd', 2, 'odd', 4, 'odd', 6, 'odd', 8, 'odd', 10]

In [11]:
list1 = ["a", "b", "c"]
list2 = [1, 2, 3]

list3 = []
for items in zip(list1, list2):
    print(items)
    list3.extend(items)

print(list3)

('a', 1)
('b', 2)
('c', 3)
['a', 1, 'b', 2, 'c', 3]

In [96]:
l1=[1,6,3,4,9]
l2=[2,6,5,4,9]
l3=[1,5,2,7,3]

l12=[x for i,x in enumerate (l1) for j,y in enumerate (l2) if i==j and x==y ]
l13=[x*y*z for i,x in enumerate (l1) for j,y in enumerate (l2) for k,z in enumerate (l3) if i==j==k  ]
l14=[((x+y+z)/3 )for i,x in enumerate (l1) for j,y in enumerate (l2) for k,z in enumerate (l3) if i==j==k  ]
l12, l13, l14

([6, 4, 9],
 [2, 180, 30, 112, 243],
 [1.3333333333333333, 5.666666666666667, 3.3333333333333335, 5.0, 7.0])

In [108]:
list(zip(l1,l2,l3))

[(1, 2, 1), (6, 6, 5), (3, 5, 2), (4, 4, 7), (9, 9, 3)]

In [97]:
[((int(x)+int(y)+int(z))/3 )for x,y,z in zip(l1,l2,l3)]
[(int(x)+int(y)+int(z))/3 for x,y,z in zip(l1,l2,l3)]

[1.3333333333333333, 5.666666666666667, 3.3333333333333335, 5.0, 7.0]

In [22]:
#to list down all the indices of a substring if present in a string
a_string = "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog"
[i for i in range(len(a_string)) if a_string.lower().startswith("the",i)]

[0, 31, 45, 76]

In [12]:
#To get the first elements from a list of tuples
rows = [(1, 2), (3, 4), (5, 6)]
[x[0] for x in rows]
[x[0] for x in rows]

[1, 3, 5]

In [25]:
l=[1,3,1,5,7,2,9]
l.remove(1) #pop removes by index and remove removes by first occurance of the value

l.pop(2)
l

[3, 1, 7, 2, 9]

In [27]:
#This is because in Python it is considered as (-)*1^2, so the result will be -1 always. So do (-1)^2
-1**2 ,(-1)**2

(-1, 1)

In [99]:
my_dict ={"Java":100, "Python":112, "C":11, "CPP":100}

[x for x in my_dict.keys() if my_dict[x]==100], [x for x in my_dict.keys() if my_dict[x]==max(list(my_dict.values()))]

(['Java', 'CPP'], ['Python'])

In [14]:
"abbxzxzxyzxzxabb".count("xzx", 0,-3)

2

In [37]:
from collections import Counter
l=[1,2,4,2,8,2]
[(x,v) for x,v in Counter(l).items() if v== max(Counter(l).values())]

[(2, 3)]

In [88]:
import re

# Sample text with patterns to replace
text = "apple123ABCd banana45 cherry7cABC date999TrfA"

# Pattern: one or more letters followed by one or more digits
pattern = r'([a-zA-Z]+)(\d+)([A-Za-z]+)' #r'([a-zA-Z]+)(\d+)'

# Replace with a custom format-using "re" library substitute this pattern by this text or another pattern in this string
# This example will put the number first, followed by the text in uppercase
result = re.sub(pattern, r'\2-\1_REPLACED\3', text)
result=re.sub(pattern, r'\2-\1_REPLACED-\3',text)
print(f"Original: {text}")
print(f"Replaced: {result}")

# Another example - remove the numbers completely
result2 = re.sub(pattern, r'\1', text)
print(f"Numbers removed: {result2}")

# Example - keep only the numbers
result3 = re.sub(pattern, r'\2', text)
print(f"Only numbers: {result3}")

# Example - surround the pattern with brackets
result4 = re.sub(pattern, r'[\1\2]', text)
print(f"With brackets: {result4}")

# Example with a more specific pattern - replace "apple" followed by numbers
specific_result = re.sub(r'(apple)(\d+)', r'\1_MODIFIED_\2', text)
print(f"Specific replacement: {specific_result}")

Original: apple123ABCd banana45 cherry7cABC date999TrfA
Replaced: 123-apple_REPLACEDABCd banana45 7-cherry_REPLACEDcABC 999-date_REPLACEDTrfA
Numbers removed: apple banana45 cherry date
Only numbers: 123 banana45 7 999
With brackets: [apple123] banana45 [cherry7] [date999]
Specific replacement: apple_MODIFIED_123ABCd banana45 cherry7cABC date999TrfA

In [118]:
list_extend = [1, 2, 3]
list_extend.extend([4, 5, 6])
list_append = [1, 2, 3]
list_append.append(4) 
list_extend, list_append, list_append.append([4,5])
#list_extend.extend(4) #extend works with [] only

([1, 2, 3, 4, 5, 6], [1, 2, 3, 4, [4, 5]], None)